/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.up = function (knex) {
  const medications = [
    // --- GASTROINTESTINAL SYSTEM ---
    {
      DrugGroup: "GASTROINTESTINAL SYSTEM",
      DrugSubGroup: "Dyspepsia & GORD",
      TypeofDrug: "Antacids (PRN, symptom relief)",
      medication: "Aluminium hydroxide",
      dose: "500–1000 mg PO up to QID PRN.",
    },
    {
      DrugGroup: "GASTROINTESTINAL SYSTEM",
      DrugSubGroup: "Dyspepsia & GORD",
      TypeofDrug: "Antacids (PRN, symptom relief)",
      medication: "Magnesium hydroxide",
      dose: "500–1000 mg PO up to QID PRN.",
    },
    {
      DrugGroup: "GASTROINTESTINAL SYSTEM",
      DrugSubGroup: "Dyspepsia & GORD",
      TypeofDrug: "Antacids (PRN, symptom relief)",
      medication: "Magnesium trisilicate",
      dose: "500–1000 mg PO up to QID PRN.",
    },
    {
      DrugGroup: "GASTROINTESTINAL SYSTEM",
      DrugSubGroup: "Dyspepsia & GORD",
      TypeofDrug: "Antacids (PRN, symptom relief)",
      medication: "Calcium carbonate",
      dose: "500–1500 mg PO 1–3×/day PRN.",
    },
    {
      DrugGroup: "GASTROINTESTINAL SYSTEM",
      DrugSubGroup: "Dyspepsia & GORD",
      TypeofDrug: "Alginates",
      medication: "Sodium alginate + antacid combos",
      dose: "10–20 mL PO after meals & at bedtime (up to QID).",
    },
    {
      DrugGroup: "GASTROINTESTINAL SYSTEM",
      DrugSubGroup: "Dyspepsia & GORD",
      TypeofDrug: "Proton Pump Inhibitors (PPIs)",
      medication: "Omeprazole",
      dose: "20 mg OD (up to 40 mg OD).",
    },
    {
      DrugGroup: "GASTROINTESTINAL SYSTEM",
      DrugSubGroup: "Dyspepsia & GORD",
      TypeofDrug: "Proton Pump Inhibitors (PPIs)",
      medication: "Lansoprazole",
      dose: "15–30 mg OD.",
    },
    {
      DrugGroup: "GASTROINTESTINAL SYSTEM",
      DrugSubGroup: "Dyspepsia & GORD",
      TypeofDrug: "Proton Pump Inhibitors (PPIs)",
      medication: "Esomeprazole",
      dose: "20–40 mg OD.",
    },
    {
      DrugGroup: "GASTROINTESTINAL SYSTEM",
      DrugSubGroup: "Dyspepsia & GORD",
      TypeofDrug: "Proton Pump Inhibitors (PPIs)",
      medication: "Pantoprazole",
      dose: "20–40 mg OD.",
    },
    {
      DrugGroup: "GASTROINTESTINAL SYSTEM",
      DrugSubGroup: "Dyspepsia & GORD",
      TypeofDrug: "Proton Pump Inhibitors (PPIs)",
      medication: "Rabeprazole",
      dose: "20 mg OD.",
    },
    {
      DrugGroup: "GASTROINTESTINAL SYSTEM",
      DrugSubGroup: "Dyspepsia & GORD",
      TypeofDrug: "H2-receptor antagonists",
      medication: "Famotidine",
      dose: "20 mg BD or 40 mg ON.",
    },
    {
      DrugGroup: "GASTROINTESTINAL SYSTEM",
      DrugSubGroup: "Dyspepsia & GORD",
      TypeofDrug: "H2-receptor antagonists",
      medication: "Nizatidine",
      dose: "150 mg BD or 300 mg ON.",
    },
    {
      DrugGroup: "GASTROINTESTINAL SYSTEM",
      DrugSubGroup: "Dyspepsia & GORD",
      TypeofDrug: "P-CABs",
      medication: "Vonoprazan (where available)",
      dose: "10–20 mg OD.",
    },
    {
      DrugGroup: "GASTROINTESTINAL SYSTEM",
      DrugSubGroup: "Antiemetics",
      TypeofDrug: "Dopamine antagonists",
      medication: "Metoclopramide",
      dose: "10 mg PO/IV/IM up to TDS (short-term).",
    },
    {
      DrugGroup: "GASTROINTESTINAL SYSTEM",
      DrugSubGroup: "Antiemetics",
      TypeofDrug: "Dopamine antagonists",
      medication: "Prochlorperazine",
      dose: "5–10 mg PO 2–3×/day; buccal 3–6 mg BD.",
    },
    {
      DrugGroup: "GASTROINTESTINAL SYSTEM",
      DrugSubGroup: "Antiemetics",
      TypeofDrug: "Dopamine antagonists",
      medication: "Domperidone",
      dose: "10 mg PO up to TDS (restricted, QT risk).",
    },
    {
      DrugGroup: "GASTROINTESTINAL SYSTEM",
      DrugSubGroup: "Antiemetics",
      TypeofDrug: "5-HT3 antagonists",
      medication: "Ondansetron",
      dose: "4–8 mg PO/IV; chemo: 8 mg pre-chemo ± repeat.",
    },
    {
      DrugGroup: "GASTROINTESTINAL SYSTEM",
      DrugSubGroup: "Antiemetics",
      TypeofDrug: "Antihistamines (N&V)",
      medication: "Cyclizine",
      dose: "50 mg PO/IV/IM up to TDS.",
    },
    {
      DrugGroup: "GASTROINTESTINAL SYSTEM",
      DrugSubGroup: "Antiemetics",
      TypeofDrug: "Antihistamines (N&V)",
      medication: "Promethazine",
      dose: "10–25 mg 2–3×/day or 25 mg ON.",
    },
    {
      DrugGroup: "GASTROINTESTINAL SYSTEM",
      DrugSubGroup: "Disorders of Bowel Motility",
      TypeofDrug: "Laxatives (Bulk)",
      medication: "Ispaghula husk",
      dose: "1 sachet 1–2×/day with water.",
    },
    {
      DrugGroup: "GASTROINTESTINAL SYSTEM",
      DrugSubGroup: "Disorders of Bowel Motility",
      TypeofDrug: "Laxatives (Osmotic)",
      medication: "Lactulose",
      dose: "15 mL BD–TDS, titrate.",
    },
    {
      DrugGroup: "GASTROINTESTINAL SYSTEM",
      DrugSubGroup: "Disorders of Bowel Motility",
      TypeofDrug: "Laxatives (Osmotic)",
      medication: "Macrogol (PEG)",
      dose: "1–3 sachets/day depending on regimen.",
    },
    {
      DrugGroup: "GASTROINTESTINAL SYSTEM",
      DrugSubGroup: "Disorders of Bowel Motility",
      TypeofDrug: "Laxatives (Stimulant)",
      medication: "Senna",
      dose: "7.5–15 mg ON (up to 30 mg).",
    },
    {
      DrugGroup: "GASTROINTESTINAL SYSTEM",
      DrugSubGroup: "Disorders of Bowel Motility",
      TypeofDrug: "Laxatives (Stimulant)",
      medication: "Bisacodyl",
      dose: "5–10 mg ON PO; 10 mg PR.",
    },
    {
      DrugGroup: "GASTROINTESTINAL SYSTEM",
      DrugSubGroup: "Disorders of Bowel Motility",
      TypeofDrug: "Laxatives (Stool softener)",
      medication: "Docusate",
      dose: "100–300 mg/day in divided doses.",
    },
    {
      DrugGroup: "GASTROINTESTINAL SYSTEM",
      DrugSubGroup: "Disorders of Bowel Motility",
      TypeofDrug: "Antidiarrhoeals",
      medication: "Loperamide",
      dose: "4 mg stat then 2 mg after each loose stool, max ~16 mg/day.",
    },
    {
      DrugGroup: "GASTROINTESTINAL SYSTEM",
      DrugSubGroup: "Inflammatory Bowel Disease",
      TypeofDrug: "Aminosalicylates",
      medication: "Mesalazine",
      dose: "often 2–4 g/day PO in divided doses ± rectal prep.",
    },
    {
      DrugGroup: "GASTROINTESTINAL SYSTEM",
      DrugSubGroup: "Inflammatory Bowel Disease",
      TypeofDrug: "Corticosteroids (IBD)",
      medication: "Prednisolone",
      dose: "30–40 mg OD, taper over weeks.",
    },
    {
      DrugGroup: "GASTROINTESTINAL SYSTEM",
      DrugSubGroup: "Liver disease drugs",
      TypeofDrug: "Bile acid",
      medication: "Ursodeoxycholic acid",
      dose: "10–15 mg/kg/day PO in divided doses.",
    },

    // --- CARDIOVASCULAR SYSTEM ---
    {
      DrugGroup: "CARDIOVASCULAR SYSTEM",
      DrugSubGroup: "Diuretics",
      TypeofDrug: "Loop",
      medication: "Furosemide",
      dose: "20–40 mg PO OD (up to 80–120 mg+); 20–40 mg IV acute.",
    },
    {
      DrugGroup: "CARDIOVASCULAR SYSTEM",
      DrugSubGroup: "Diuretics",
      TypeofDrug: "Loop",
      medication: "Bumetanide",
      dose: "1 mg PO OD (up to 2–3 mg).",
    },
    {
      DrugGroup: "CARDIOVASCULAR SYSTEM",
      DrugSubGroup: "Diuretics",
      TypeofDrug: "Loop",
      medication: "Torasemide",
      dose: "5–20 mg PO OD.",
    },
    {
      DrugGroup: "CARDIOVASCULAR SYSTEM",
      DrugSubGroup: "Diuretics",
      TypeofDrug: "Thiazide / thiazide-like",
      medication: "Bendroflumethiazide",
      dose: "2.5 mg OD (HTN); 5–10 mg OD (oedema).",
    },
    {
      DrugGroup: "CARDIOVASCULAR SYSTEM",
      DrugSubGroup: "Diuretics",
      TypeofDrug: "Thiazide / thiazide-like",
      medication: "Indapamide",
      dose: "1.5 mg MR OD or 2.5 mg OD.",
    },
    {
      DrugGroup: "CARDIOVASCULAR SYSTEM",
      DrugSubGroup: "Diuretics",
      TypeofDrug: "Potassium-sparing",
      medication: "Spironolactone",
      dose: "25–50 mg OD (HF/oedema; up to 100 mg+ in ascites).",
    },
    {
      DrugGroup: "CARDIOVASCULAR SYSTEM",
      DrugSubGroup: "Beta-blockers",
      TypeofDrug: "Beta-blocker",
      medication: "Bisoprolol",
      dose: "2.5–5 mg OD → 5–10 mg OD (max 20 mg).",
    },
    {
      DrugGroup: "CARDIOVASCULAR SYSTEM",
      DrugSubGroup: "Beta-blockers",
      TypeofDrug: "Beta-blocker",
      medication: "Atenolol",
      dose: "25–50 mg OD → 100 mg OD.",
    },
    {
      DrugGroup: "CARDIOVASCULAR SYSTEM",
      DrugSubGroup: "Beta-blockers",
      TypeofDrug: "Beta-blocker",
      medication: "Propranolol",
      dose: "10–40 mg TDS–QDS (arrhythmias/anxiety); regimens vary.",
    },
    {
      DrugGroup: "CARDIOVASCULAR SYSTEM",
      DrugSubGroup: "Beta-blockers",
      TypeofDrug: "Beta-blocker",
      medication: "Carvedilol",
      dose: "3.125 mg BD → up to 25 mg BD (HF).",
    },
    {
      DrugGroup: "CARDIOVASCULAR SYSTEM",
      DrugSubGroup: "Vasodilators",
      TypeofDrug: "Nitrates",
      medication: "GTN SL",
      dose: "300–600 micrograms under tongue; repeat to max ~1.2 mg/15 min.",
    },
    {
      DrugGroup: "CARDIOVASCULAR SYSTEM",
      DrugSubGroup: "Vasodilators",
      TypeofDrug: "Nitrates",
      medication: "Isosorbide mononitrate",
      dose: "20–40 mg BD, or MR 40–60 mg OD.",
    },
    {
      DrugGroup: "CARDIOVASCULAR SYSTEM",
      DrugSubGroup: "Calcium-channel blockers",
      TypeofDrug: "CCB",
      medication: "Amlodipine",
      dose: "5 mg OD → 10 mg OD.",
    },
    {
      DrugGroup: "CARDIOVASCULAR SYSTEM",
      DrugSubGroup: "Calcium-channel blockers",
      TypeofDrug: "CCB",
      medication: "Nifedipine MR",
      dose: "20–60 mg BD or 30–60 mg OD (product-specific).",
    },
    {
      DrugGroup: "CARDIOVASCULAR SYSTEM",
      DrugSubGroup: "Calcium-channel blockers",
      TypeofDrug: "CCB",
      medication: "Diltiazem MR",
      dose: "120–360 mg/day.",
    },
    {
      DrugGroup: "CARDIOVASCULAR SYSTEM",
      DrugSubGroup: "ACE inhibitors",
      TypeofDrug: "ACEi",
      medication: "Ramipril",
      dose: "1.25–2.5 mg OD → 5–10 mg OD.",
    },
    {
      DrugGroup: "CARDIOVASCULAR SYSTEM",
      DrugSubGroup: "ACE inhibitors",
      TypeofDrug: "ACEi",
      medication: "Lisinopril",
      dose: "5–10 mg OD → 10–20 mg (max ~80 mg).",
    },
    {
      DrugGroup: "CARDIOVASCULAR SYSTEM",
      DrugSubGroup: "ACE inhibitors",
      TypeofDrug: "ACEi",
      medication: "Enalapril",
      dose: "5 mg OD → 10–20 mg/day.",
    },
    {
      DrugGroup: "CARDIOVASCULAR SYSTEM",
      DrugSubGroup: "ARBs",
      TypeofDrug: "ARB",
      medication: "Losartan",
      dose: "50 mg OD → 100 mg OD.",
    },
    {
      DrugGroup: "CARDIOVASCULAR SYSTEM",
      DrugSubGroup: "ARBs",
      TypeofDrug: "ARB",
      medication: "Candesartan",
      dose: "8 mg OD → 32 mg OD.",
    },
    {
      DrugGroup: "CARDIOVASCULAR SYSTEM",
      DrugSubGroup: "ARBs",
      TypeofDrug: "ARB",
      medication: "Valsartan",
      dose: "80–160 mg OD → 320 mg/day.",
    },
    {
      DrugGroup: "CARDIOVASCULAR SYSTEM",
      DrugSubGroup: "Heart failure medications",
      TypeofDrug: "ARNI",
      medication: "Sacubitril/valsartan",
      dose: "49/51 mg BD (or 24/26 mg BD) → 97/103 mg BD as tolerated.",
    },
    {
      DrugGroup: "CARDIOVASCULAR SYSTEM",
      DrugSubGroup: "Heart failure medications",
      TypeofDrug: "SGLT2 inhibitor",
      medication: "Dapagliflozin",
      dose: "10 mg OD.",
    },
    {
      DrugGroup: "CARDIOVASCULAR SYSTEM",
      DrugSubGroup: "Antiarrhythmics",
      TypeofDrug: "Class III",
      medication: "Amiodarone",
      dose: "200 mg TDS 1 wk → 200 mg BD 1 wk → 200 mg OD (typical PO loading).",
    },
    {
      DrugGroup: "CARDIOVASCULAR SYSTEM",
      DrugSubGroup: "Antiarrhythmics",
      TypeofDrug: "Glycoside",
      medication: "Digoxin",
      dose: "125–250 micrograms OD maintenance (loading varies).",
    },
    {
      DrugGroup: "CARDIOVASCULAR SYSTEM",
      DrugSubGroup: "Anticoagulants",
      TypeofDrug: "Heparins",
      medication: "Enoxaparin",
      dose: "1 mg/kg SC q12h or 1.5 mg/kg OD (VTE treatment).",
    },
    {
      DrugGroup: "CARDIOVASCULAR SYSTEM",
      DrugSubGroup: "Anticoagulants",
      TypeofDrug: "DOACs",
      medication: "Apixaban",
      dose: "5 mg BD (2.5 mg BD in some).",
    },
    {
      DrugGroup: "CARDIOVASCULAR SYSTEM",
      DrugSubGroup: "Anticoagulants",
      TypeofDrug: "DOACs",
      medication: "Rivaroxaban",
      dose: "20 mg OD with food (15 mg OD in some renal impairment).",
    },
    {
      DrugGroup: "CARDIOVASCULAR SYSTEM",
      DrugSubGroup: "Anticoagulants",
      TypeofDrug: "Warfarin",
      medication: "Warfarin",
      dose: "~5 mg OD start (lower in elderly); maintenance 1–10 mg OD by INR.",
    },
    {
      DrugGroup: "CARDIOVASCULAR SYSTEM",
      DrugSubGroup: "Antiplatelets",
      TypeofDrug: "Antiplatelet",
      medication: "Aspirin",
      dose: "75–100 mg OD.",
    },
    {
      DrugGroup: "CARDIOVASCULAR SYSTEM",
      DrugSubGroup: "Antiplatelets",
      TypeofDrug: "Antiplatelet",
      medication: "Clopidogrel",
      dose: "75 mg OD (LD 300–600 mg in ACS/PCI).",
    },
    {
      DrugGroup: "CARDIOVASCULAR SYSTEM",
      DrugSubGroup: "Lipid-lowering agents",
      TypeofDrug: "Statins",
      medication: "Atorvastatin",
      dose: "10–80 mg OD (20–80 mg typical high-intensity).",
    },
    {
      DrugGroup: "CARDIOVASCULAR SYSTEM",
      DrugSubGroup: "Lipid-lowering agents",
      TypeofDrug: "Statins",
      medication: "Simvastatin",
      dose: "10–40 mg ON.",
    },
    {
      DrugGroup: "CARDIOVASCULAR SYSTEM",
      DrugSubGroup: "Lipid-lowering agents",
      TypeofDrug: "Statins",
      medication: "Rosuvastatin",
      dose: "5–40 mg OD.",
    },

    // --- RESPIRATORY SYSTEM ---
    {
      DrugGroup: "RESPIRATORY SYSTEM",
      DrugSubGroup: "SABA",
      TypeofDrug: "SABA",
      medication: "Salbutamol",
      dose: "100–200 micrograms (1–2 puffs) up to QID PRN; neb 2.5–5 mg q4–6h.",
    },
    {
      DrugGroup: "RESPIRATORY SYSTEM",
      DrugSubGroup: "LABA",
      TypeofDrug: "LABA",
      medication: "Salmeterol",
      dose: "50 micrograms BD.",
    },
    {
      DrugGroup: "RESPIRATORY SYSTEM",
      DrugSubGroup: "ICS",
      TypeofDrug: "ICS",
      medication: "Beclometasone",
      dose: "200–400 micrograms BD.",
    },
    {
      DrugGroup: "RESPIRATORY SYSTEM",
      DrugSubGroup: "ICS",
      TypeofDrug: "ICS",
      medication: "Budesonide",
      dose: "200–400 micrograms BD.",
    },
    {
      DrugGroup: "RESPIRATORY SYSTEM",
      DrugSubGroup: "LABA/ICS combos",
      TypeofDrug: "Combo",
      medication: "Salmeterol/Fluticasone",
      dose: "50/250 micrograms BD (various strengths).",
    },
    {
      DrugGroup: "RESPIRATORY SYSTEM",
      DrugSubGroup: "LAMA",
      TypeofDrug: "LAMA",
      medication: "Tiotropium",
      dose: "18 micrograms DPI OD or 2 puffs Respimat OD.",
    },
    {
      DrugGroup: "RESPIRATORY SYSTEM",
      DrugSubGroup: "Leukotriene receptor antagonists",
      TypeofDrug: "LTRA",
      medication: "Montelukast",
      dose: "10 mg OD (adult).",
    },

    // --- CNS ---
    {
      DrugGroup: "CNS",
      DrugSubGroup: "Hypnotics & anxiolytics",
      TypeofDrug: "Benzodiazepines",
      medication: "Diazepam",
      dose: "2–10 mg up to TDS (short-term).",
    },
    {
      DrugGroup: "CNS",
      DrugSubGroup: "Hypnotics & anxiolytics",
      TypeofDrug: "Benzodiazepines",
      medication: "Lorazepam",
      dose: "1–4 mg/day divided.",
    },
    {
      DrugGroup: "CNS",
      DrugSubGroup: "Hypnotics & anxiolytics",
      TypeofDrug: "Z-drugs",
      medication: "Zopiclone",
      dose: "7.5 mg ON (3.75 mg in elderly).",
    },
    {
      DrugGroup: "CNS",
      DrugSubGroup: "Antipsychotics",
      TypeofDrug: "Typical",
      medication: "Haloperidol",
      dose: "1–5 mg PO BD–TDS; IM 2–10 mg for acute agitation.",
    },
    {
      DrugGroup: "CNS",
      DrugSubGroup: "Antipsychotics",
      TypeofDrug: "Atypical",
      medication: "Risperidone",
      dose: "1 mg BD → 4–6 mg/day.",
    },
    {
      DrugGroup: "CNS",
      DrugSubGroup: "Antipsychotics",
      TypeofDrug: "Atypical",
      medication: "Olanzapine",
      dose: "5–20 mg OD.",
    },
    {
      DrugGroup: "CNS",
      DrugSubGroup: "Antipsychotics",
      TypeofDrug: "Atypical",
      medication: "Quetiapine",
      dose: "150–800 mg/day (divided or MR).",
    },
    {
      DrugGroup: "CNS",
      DrugSubGroup: "Antidepressants",
      TypeofDrug: "SSRIs",
      medication: "Sertraline",
      dose: "50 mg OD → 200 mg OD.",
    },
    {
      DrugGroup: "CNS",
      DrugSubGroup: "Antidepressants",
      TypeofDrug: "SSRIs",
      medication: "Citalopram",
      dose: "20 mg OD (max 40 mg; often 20 mg in high-risk pts).",
    },
    {
      DrugGroup: "CNS",
      DrugSubGroup: "Antidepressants",
      TypeofDrug: "SSRIs",
      medication: "Fluoxetine",
      dose: "20 mg OD → 60 mg/day.",
    },
    {
      DrugGroup: "CNS",
      DrugSubGroup: "Antidepressants",
      TypeofDrug: "SNRIs",
      medication: "Venlafaxine",
      dose: "75 mg/day → 225 mg/day (or higher specialist).",
    },
    {
      DrugGroup: "CNS",
      DrugSubGroup: "Antidepressants",
      TypeofDrug: "TCAs",
      medication: "Amitriptyline",
      dose: "75–150 mg/day (depression); 10–50 mg ON (pain).",
    },
    {
      DrugGroup: "CNS",
      DrugSubGroup: "Antidepressants",
      TypeofDrug: "Atypical",
      medication: "Mirtazapine",
      dose: "15–45 mg ON.",
    },
    {
      DrugGroup: "CNS",
      DrugSubGroup: "Bipolar drugs",
      TypeofDrug: "Mood stabilizer",
      medication: "Lithium",
      dose: "dose to level 0.4–1.0 mmol/L (often 400–1200 mg/day).",
    },
    {
      DrugGroup: "CNS",
      DrugSubGroup: "Antiepileptics",
      TypeofDrug: "Antiepileptics",
      medication: "Sodium valproate",
      dose: "600–2000 mg/day.",
    },
    {
      DrugGroup: "CNS",
      DrugSubGroup: "Antiepileptics",
      TypeofDrug: "Antiepileptics",
      medication: "Levetiracetam",
      dose: "500–1500 mg BD.",
    },
    {
      DrugGroup: "CNS",
      DrugSubGroup: "Parkinson’s",
      TypeofDrug: "Dopaminergic",
      medication: "Levodopa/carbidopa",
      dose: "start ~62.5–100 mg levodopa TDS → 300–1000 mg/day levodopa equivalent.",
    },

    // --- INFECTIONS / ANTIMICROBIALS ---
    {
      DrugGroup: "INFECTIONS / ANTIMICROBIALS",
      DrugSubGroup: "Antibiotics",
      TypeofDrug: "Penicillins",
      medication: "Amoxicillin",
      dose: "500 mg TDS (up to 1 g TDS severe).",
    },
    {
      DrugGroup: "INFECTIONS / ANTIMICROBIALS",
      DrugSubGroup: "Antibiotics",
      TypeofDrug: "Penicillins",
      medication: "Co-amoxiclav",
      dose: "500/125 mg TDS or 875/125 mg BD.",
    },
    {
      DrugGroup: "INFECTIONS / ANTIMICROBIALS",
      DrugSubGroup: "Antibiotics",
      TypeofDrug: "Penicillins",
      medication: "Flucloxacillin",
      dose: "500 mg QID (up to 1 g QID severe).",
    },
    {
      DrugGroup: "INFECTIONS / ANTIMICROBIALS",
      DrugSubGroup: "Antibiotics",
      TypeofDrug: "Penicillins",
      medication: "Piperacillin/tazobactam",
      dose: "4.5 g IV every 6–8 hours.",
    },
    {
      DrugGroup: "INFECTIONS / ANTIMICROBIALS",
      DrugSubGroup: "Antibiotics",
      TypeofDrug: "Cephalosporins",
      medication: "Cefalexin",
      dose: "250–500 mg every 6–8 hours (up to 1 g QID).",
    },
    {
      DrugGroup: "INFECTIONS / ANTIMICROBIALS",
      DrugSubGroup: "Antibiotics",
      TypeofDrug: "Cephalosporins",
      medication: "Ceftriaxone",
      dose: "1–2 g OD (2 g BD meningitis).",
    },
    {
      DrugGroup: "INFECTIONS / ANTIMICROBIALS",
      DrugSubGroup: "Antibiotics",
      TypeofDrug: "Macrolides",
      medication: "Clarithromycin",
      dose: "250–500 mg BD.",
    },
    {
      DrugGroup: "INFECTIONS / ANTIMICROBIALS",
      DrugSubGroup: "Antibiotics",
      TypeofDrug: "Macrolides",
      medication: "Azithromycin",
      dose: "500 mg OD ×3 days (or 500 mg day 1 then 250 mg OD days 2–5).",
    },
    {
      DrugGroup: "INFECTIONS / ANTIMICROBIALS",
      DrugSubGroup: "Antibiotics",
      TypeofDrug: "Tetracyclines",
      medication: "Doxycycline",
      dose: "200 mg day 1 then 100 mg OD (or BD severe).",
    },
    {
      DrugGroup: "INFECTIONS / ANTIMICROBIALS",
      DrugSubGroup: "Antibiotics",
      TypeofDrug: "Aminoglycosides",
      medication: "Gentamicin",
      dose: "5–7 mg/kg IV OD (protocol-based).",
    },
    {
      DrugGroup: "INFECTIONS / ANTIMICROBIALS",
      DrugSubGroup: "Antibiotics",
      TypeofDrug: "Fluoroquinolones",
      medication: "Ciprofloxacin",
      dose: "500 mg BD (up to 750 mg BD).",
    },
    {
      DrugGroup: "INFECTIONS / ANTIMICROBIALS",
      DrugSubGroup: "Antibiotics",
      TypeofDrug: "Fluoroquinolones",
      medication: "Levofloxacin",
      dose: "500–750 mg OD.",
    },
    {
      DrugGroup: "INFECTIONS / ANTIMICROBIALS",
      DrugSubGroup: "Antibiotics",
      TypeofDrug: "Glycopeptides",
      medication: "Vancomycin",
      dose: "20–25 mg/kg loading → 15–20 mg/kg every 8–12 hours (level-guided).",
    },
    {
      DrugGroup: "INFECTIONS / ANTIMICROBIALS",
      DrugSubGroup: "Antibiotics",
      TypeofDrug: "Sulfonamides & Trimethoprim",
      medication: "Trimethoprim",
      dose: "200 mg BD.",
    },
    {
      DrugGroup: "INFECTIONS / ANTIMICROBIALS",
      DrugSubGroup: "Antibiotics",
      TypeofDrug: "Sulfonamides & Trimethoprim",
      medication: "Co-trimoxazole",
      dose: "960 mg BD.",
    },
    {
      DrugGroup: "INFECTIONS / ANTIMICROBIALS",
      DrugSubGroup: "Antibiotics",
      TypeofDrug: "Nitroimidazoles",
      medication: "Metronidazole",
      dose: "400 mg TDS or 500 mg IV TDS.",
    },
    {
      DrugGroup: "INFECTIONS / ANTIMICROBIALS",
      DrugSubGroup: "Antifungals",
      TypeofDrug: "Azoles",
      medication: "Fluconazole",
      dose: "150 mg stat (thrush) or 100–400 mg/day systemic.",
    },
    {
      DrugGroup: "INFECTIONS / ANTIMICROBIALS",
      DrugSubGroup: "Antivirals",
      TypeofDrug: "Herpes antivirals",
      medication: "Aciclovir",
      dose: "400 mg TDS (higher for VZV e.g. 800 mg 5×/day).",
    },

    // --- ENDOCRINE SYSTEM ---
    {
      DrugGroup: "ENDOCRINE SYSTEM",
      DrugSubGroup: "Diabetes drugs",
      TypeofDrug: "Biguanide",
      medication: "Metformin IR",
      dose: "start 500 mg OD–BD → 1 g BD (max 2–3 g/day).",
    },
    {
      DrugGroup: "ENDOCRINE SYSTEM",
      DrugSubGroup: "Diabetes drugs",
      TypeofDrug: "Sulfonylureas",
      medication: "Gliclazide",
      dose: "40–80 mg OD → up to 160 mg BD (max 320 mg/day).",
    },
    {
      DrugGroup: "ENDOCRINE SYSTEM",
      DrugSubGroup: "Diabetes drugs",
      TypeofDrug: "DPP-4 inhibitors",
      medication: "Sitagliptin",
      dose: "100 mg OD.",
    },
    {
      DrugGroup: "ENDOCRINE SYSTEM",
      DrugSubGroup: "Diabetes drugs",
      TypeofDrug: "SGLT2 inhibitors",
      medication: "Empagliflozin",
      dose: "10–25 mg OD.",
    },
    {
      DrugGroup: "ENDOCRINE SYSTEM",
      DrugSubGroup: "Diabetes drugs",
      TypeofDrug: "Insulins",
      medication: "Basal insulin",
      dose: "start ~10 units OD or 0.2 units/kg.",
    },
    {
      DrugGroup: "ENDOCRINE SYSTEM",
      DrugSubGroup: "Corticosteroids",
      TypeofDrug: "Corticosteroids",
      medication: "Prednisolone",
      dose: "5–60 mg OD depending on indication.",
    },
    {
      DrugGroup: "ENDOCRINE SYSTEM",
      DrugSubGroup: "Corticosteroids",
      TypeofDrug: "Corticosteroids",
      medication: "Hydrocortisone (crisis)",
      dose: "100 mg IV stat then 50–100 mg IV/IM q6h.",
    },
    {
      DrugGroup: "ENDOCRINE SYSTEM",
      DrugSubGroup: "Thyroid drugs",
      TypeofDrug: "Thyroid hormone",
      medication: "Levothyroxine",
      dose: "usual 100–200 micrograms OD (start 25–50 micrograms in elderly/cardiac).",
    },
    {
      DrugGroup: "ENDOCRINE SYSTEM",
      DrugSubGroup: "Thyroid drugs",
      TypeofDrug: "Antithyroid",
      medication: "Carbimazole",
      dose: "15–40 mg/day initially → 5–15 mg/day maintenance.",
    },
    {
      DrugGroup: "ENDOCRINE SYSTEM",
      DrugSubGroup: "Contraception",
      TypeofDrug: "COC",
      medication: "Combined oral contraception",
      dose: "1 tablet OD for 21 days then 7-day break/placebo.",
    },

    // --- MUSCULOSKELETAL & JOINT ---
    {
      DrugGroup: "MUSCULOSKELETAL & JOINT",
      DrugSubGroup: "NSAIDs",
      TypeofDrug: "NSAIDs",
      medication: "Ibuprofen",
      dose: "200–400 mg TDS–QDS (max 2.4 g/day).",
    },
    {
      DrugGroup: "MUSCULOSKELETAL & JOINT",
      DrugSubGroup: "NSAIDs",
      TypeofDrug: "NSAIDs",
      medication: "Naproxen",
      dose: "250–500 mg BD (max 1 g/day).",
    },
    {
      DrugGroup: "MUSCULOSKELETAL & JOINT",
      DrugSubGroup: "NSAIDs",
      TypeofDrug: "NSAIDs",
      medication: "Diclofenac",
      dose: "50 mg TDS (max 150 mg/day).",
    },
    {
      DrugGroup: "MUSCULOSKELETAL & JOINT",
      DrugSubGroup: "Muscle relaxants",
      TypeofDrug: "Muscle relaxants",
      medication: "Baclofen",
      dose: "5 mg TDS → up to 20 mg TDS.",
    },
    {
      DrugGroup: "MUSCULOSKELETAL & JOINT",
      DrugSubGroup: "Osteoporosis",
      TypeofDrug: "Bisphosphonates",
      medication: "Alendronic acid",
      dose: "70 mg weekly or 10 mg OD.",
    },
    {
      DrugGroup: "MUSCULOSKELETAL & JOINT",
      DrugSubGroup: "Gout",
      TypeofDrug: "Gout",
      medication: "Colchicine",
      dose: "500 micrograms 2–4×/day short course.",
    },
    {
      DrugGroup: "MUSCULOSKELETAL & JOINT",
      DrugSubGroup: "Gout",
      TypeofDrug: "Gout",
      medication: "Allopurinol",
      dose: "start 100 mg OD → 300 mg OD (max 900 mg).",
    },

    // --- EYE ---
    {
      DrugGroup: "EYE",
      DrugSubGroup: "",
      TypeofDrug: "Glaucoma",
      medication: "Latanoprost",
      dose: "1 drop ON.",
    },
    {
      DrugGroup: "EYE",
      DrugSubGroup: "",
      TypeofDrug: "Glaucoma",
      medication: "Timolol",
      dose: "1 drop BD.",
    },
    {
      DrugGroup: "EYE",
      DrugSubGroup: "",
      TypeofDrug: "Glaucoma",
      medication: "Dorzolamide",
      dose: "1 drop TDS.",
    },
    {
      DrugGroup: "EYE",
      DrugSubGroup: "",
      TypeofDrug: "Glaucoma",
      medication: "Brimonidine",
      dose: "1 drop BD–TDS.",
    },
    {
      DrugGroup: "EYE",
      DrugSubGroup: "",
      TypeofDrug: "Anti-infective",
      medication: "Chloramphenicol",
      dose: "1 drop QDS (or q2h initially) for 5 days.",
    },
    {
      DrugGroup: "EYE",
      DrugSubGroup: "",
      TypeofDrug: "Anti-infective",
      medication: "Fusidic acid",
      dose: "1 drop BD.",
    },
    {
      DrugGroup: "EYE",
      DrugSubGroup: "",
      TypeofDrug: "Anti-inflammatory",
      medication: "Prednisolone eye drops",
      dose: "1 drop q1–2h then taper.",
    },
    {
      DrugGroup: "EYE",
      DrugSubGroup: "",
      TypeofDrug: "Lubricants",
      medication: "Hypromellose",
      dose: "1–2 drops PRN.",
    },
    {
      DrugGroup: "EYE",
      DrugSubGroup: "",
      TypeofDrug: "Lubricants",
      medication: "Sodium hyaluronate",
      dose: "1–2 drops PRN.",
    },

    // --- EAR, NOSE & OROPHARYNX ---
    {
      DrugGroup: "EAR, NOSE & OROPHARYNX",
      DrugSubGroup: "",
      TypeofDrug: "Nasal steroids",
      medication: "Beclometasone",
      dose: "50 micrograms/spray, 1–2 sprays/nostril BD.",
    },
    {
      DrugGroup: "EAR, NOSE & OROPHARYNX",
      DrugSubGroup: "",
      TypeofDrug: "Nasal steroids",
      medication: "Fluticasone",
      dose: "50 micrograms/spray, 1–2 sprays/nostril OD–BD.",
    },
    {
      DrugGroup: "EAR, NOSE & OROPHARYNX",
      DrugSubGroup: "",
      TypeofDrug: "Nasal steroids",
      medication: "Mometasone",
      dose: "50 micrograms/spray, 1–2 sprays/nostril OD.",
    },
    {
      DrugGroup: "EAR, NOSE & OROPHARYNX",
      DrugSubGroup: "",
      TypeofDrug: "Antihistamines",
      medication: "Cetirizine",
      dose: "10 mg OD.",
    },
    {
      DrugGroup: "EAR, NOSE & OROPHARYNX",
      DrugSubGroup: "",
      TypeofDrug: "Antihistamines",
      medication: "Loratadine",
      dose: "10 mg OD.",
    },
    {
      DrugGroup: "EAR, NOSE & OROPHARYNX",
      DrugSubGroup: "",
      TypeofDrug: "Antihistamines",
      medication: "Fexofenadine",
      dose: "120–180 mg OD.",
    },
    {
      DrugGroup: "EAR, NOSE & OROPHARYNX",
      DrugSubGroup: "",
      TypeofDrug: "Decongestants",
      medication: "Xylometazoline",
      dose: "1–2 sprays/nostril up to TDS (max 5–7 days).",
    },
    {
      DrugGroup: "EAR, NOSE & OROPHARYNX",
      DrugSubGroup: "",
      TypeofDrug: "Decongestants",
      medication: "Pseudoephedrine",
      dose: "60 mg QID short-term.",
    },
    {
      DrugGroup: "EAR, NOSE & OROPHARYNX",
      DrugSubGroup: "",
      TypeofDrug: "Throat",
      medication: "Lozenges/sprays",
      dose: "1 lozenge q2–3h PRN (product-specific).",
    },

    // --- SKIN ---
    {
      DrugGroup: "SKIN",
      DrugSubGroup: "",
      TypeofDrug: "Topical steroids",
      medication: "Hydrocortisone 1%",
      dose: "apply 1–2×/day thinly.",
    },
    {
      DrugGroup: "SKIN",
      DrugSubGroup: "",
      TypeofDrug: "Topical steroids",
      medication: "Betamethasone valerate 0.1%",
      dose: "1–2×/day.",
    },
    {
      DrugGroup: "SKIN",
      DrugSubGroup: "",
      TypeofDrug: "Topical steroids",
      medication: "Clobetasone butyrate 0.05%",
      dose: "1–2×/day.",
    },
    {
      DrugGroup: "SKIN",
      DrugSubGroup: "",
      TypeofDrug: "Topical steroids",
      medication: "Clobetasol propionate 0.05%",
      dose: "1–2×/day short courses.",
    },
    {
      DrugGroup: "SKIN",
      DrugSubGroup: "",
      TypeofDrug: "Topical antifungals",
      medication: "Clotrimazole 1%",
      dose: "BD–TDS 2–4 weeks.",
    },
    {
      DrugGroup: "SKIN",
      DrugSubGroup: "",
      TypeofDrug: "Topical antifungals",
      medication: "Terbinafine 1%",
      dose: "OD–BD 1–2 weeks.",
    },
    {
      DrugGroup: "SKIN",
      DrugSubGroup: "",
      TypeofDrug: "Topical antifungals",
      medication: "Ketoconazole",
      dose: "OD–BD 2–4 weeks.",
    },
    {
      DrugGroup: "SKIN",
      DrugSubGroup: "",
      TypeofDrug: "Topical antibacterials",
      medication: "Fusidic acid 2%",
      dose: "TDS–QDS up to 7–10 days.",
    },
    {
      DrugGroup: "SKIN",
      DrugSubGroup: "",
      TypeofDrug: "Topical antibacterials",
      medication: "Mupirocin 2%",
      dose: "TDS up to 10 days.",
    },
    {
      DrugGroup: "SKIN",
      DrugSubGroup: "",
      TypeofDrug: "Retinoids",
      medication: "Adapalene",
      dose: "thin layer OD.",
    },
    {
      DrugGroup: "SKIN",
      DrugSubGroup: "",
      TypeofDrug: "Retinoids",
      medication: "Tretinoin",
      dose: "thin layer OD.",
    },
    {
      DrugGroup: "SKIN",
      DrugSubGroup: "",
      TypeofDrug: "Retinoids",
      medication: "Isotretinoin",
      dose: "0.5–1 mg/kg/day.",
    },
    {
      DrugGroup: "SKIN",
      DrugSubGroup: "",
      TypeofDrug: "Acne systemics",
      medication: "Doxycycline",
      dose: "100 mg OD.",
    },

    // --- VACCINES & BLOOD PRODUCTS ---
    {
      DrugGroup: "VACCINES & BLOOD PRODUCTS",
      DrugSubGroup: "",
      TypeofDrug: "Vaccine",
      medication: "Standard adult vaccines",
      dose: "0.5 mL IM per schedule.",
    },
    {
      DrugGroup: "VACCINES & BLOOD PRODUCTS",
      DrugSubGroup: "",
      TypeofDrug: "Vaccine",
      medication: "Travel vaccines",
      dose: "product-specific 0.5 mL IM regimens.",
    },
    {
      DrugGroup: "VACCINES & BLOOD PRODUCTS",
      DrugSubGroup: "",
      TypeofDrug: "Blood Product",
      medication: "Human normal immunoglobulin",
      dose: "dose IU/kg per indication.",
    },
    {
      DrugGroup: "VACCINES & BLOOD PRODUCTS",
      DrugSubGroup: "",
      TypeofDrug: "Blood Product",
      medication: "Anti-D, tetanus IG, VZIG",
      dose: "IU/kg.",
    },

    // --- ANAESTHESIA ---
    {
      DrugGroup: "ANAESTHESIA",
      DrugSubGroup: "",
      TypeofDrug: "IV induction agents",
      medication: "Propofol",
      dose: "1.5–2.5 mg/kg induction; 4–12 mg/kg/h maintenance.",
    },
    {
      DrugGroup: "ANAESTHESIA",
      DrugSubGroup: "",
      TypeofDrug: "IV induction agents",
      medication: "Thiopental",
      dose: "3–5 mg/kg induction.",
    },
    {
      DrugGroup: "ANAESTHESIA",
      DrugSubGroup: "",
      TypeofDrug: "IV induction agents",
      medication: "Etomidate",
      dose: "0.2–0.3 mg/kg induction.",
    },
    {
      DrugGroup: "ANAESTHESIA",
      DrugSubGroup: "",
      TypeofDrug: "Inhalational",
      medication: "Sevoflurane",
      dose: "MAC %–based.",
    },
    {
      DrugGroup: "ANAESTHESIA",
      DrugSubGroup: "",
      TypeofDrug: "Inhalational",
      medication: "Isoflurane",
      dose: "MAC %–based.",
    },
    {
      DrugGroup: "ANAESTHESIA",
      DrugSubGroup: "",
      TypeofDrug: "Inhalational",
      medication: "Desflurane",
      dose: "MAC %–based.",
    },
    {
      DrugGroup: "ANAESTHESIA",
      DrugSubGroup: "",
      TypeofDrug: "Local anaesthetics",
      medication: "Lidocaine",
      dose: "up to ~3 mg/kg plain (7 mg/kg with adrenaline).",
    },
    {
      DrugGroup: "ANAESTHESIA",
      DrugSubGroup: "",
      TypeofDrug: "Local anaesthetics",
      medication: "Bupivacaine",
      dose: "~2 mg/kg max.",
    },
    {
      DrugGroup: "ANAESTHESIA",
      DrugSubGroup: "",
      TypeofDrug: "Local anaesthetics",
      medication: "Ropivacaine",
      dose: "agent-specific max mg/kg.",
    },
    {
      DrugGroup: "ANAESTHESIA",
      DrugSubGroup: "",
      TypeofDrug: "Neuromuscular blockers",
      medication: "Suxamethonium",
      dose: "1–1.5 mg/kg IV.",
    },
    {
      DrugGroup: "ANAESTHESIA",
      DrugSubGroup: "",
      TypeofDrug: "Neuromuscular blockers",
      medication: "Rocuronium",
      dose: "0.6–1.2 mg/kg intubation; 0.15 mg/kg maintenance.",
    },
    {
      DrugGroup: "ANAESTHESIA",
      DrugSubGroup: "",
      TypeofDrug: "Neuromuscular blockers",
      medication: "Vecuronium",
      dose: "0.08–0.1 mg/kg; 0.02 mg/kg maint.",
    },
    {
      DrugGroup: "ANAESTHESIA",
      DrugSubGroup: "",
      TypeofDrug: "Neuromuscular blockers",
      medication: "Atracurium",
      dose: "0.5 mg/kg; 0.1–0.2 mg/kg maint.",
    },
    {
      DrugGroup: "ANAESTHESIA",
      DrugSubGroup: "",
      TypeofDrug: "Reversal",
      medication: "Neostigmine",
      dose: "50 micrograms/kg IV + anticholinergic.",
    },
    {
      DrugGroup: "ANAESTHESIA",
      DrugSubGroup: "",
      TypeofDrug: "Reversal",
      medication: "Sugammadex",
      dose: "2–4 mg/kg (up to 16 mg/kg).",
    },

    // --- OBSTETRICS, GYNAE & URINARY TRACT ---
    {
      DrugGroup: "OBSTETRICS, GYNAE & URINARY TRACT",
      DrugSubGroup: "Drugs for labour",
      TypeofDrug: "Drugs for labour",
      medication: "Oxytocin",
      dose: "IV infusion 1–4 milliunits/min titrated per protocol.",
    },
    {
      DrugGroup: "OBSTETRICS, GYNAE & URINARY TRACT",
      DrugSubGroup: "Drugs for labour",
      TypeofDrug: "Drugs for labour",
      medication: "Dinoprostone",
      dose: "e.g. 10 mg vaginal pessary releasing over 24 h.",
    },
    {
      DrugGroup: "OBSTETRICS, GYNAE & URINARY TRACT",
      DrugSubGroup: "Drugs for labour",
      TypeofDrug: "Drugs for labour",
      medication: "Misoprostol",
      dose: "low-dose regimens per local protocol.",
    },
    {
      DrugGroup: "OBSTETRICS, GYNAE & URINARY TRACT",
      DrugSubGroup: "Tocolytics",
      TypeofDrug: "Tocolytics",
      medication: "Nifedipine",
      dose: "10–20 mg PO every 6–8 h (protocol-based).",
    },
    {
      DrugGroup: "OBSTETRICS, GYNAE & URINARY TRACT",
      DrugSubGroup: "Tocolytics",
      TypeofDrug: "Tocolytics",
      medication: "Atosiban",
      dose: "IV bolus + infusion (weight/protocol-based).",
    },
    {
      DrugGroup: "OBSTETRICS, GYNAE & URINARY TRACT",
      DrugSubGroup: "Antifibrinolytics",
      TypeofDrug: "Antifibrinolytics",
      medication: "Tranexamic acid",
      dose: "1 g IV over 10 min for PPH; 1 g PO TDS menorrhagia.",
    },
    {
      DrugGroup: "OBSTETRICS, GYNAE & URINARY TRACT",
      DrugSubGroup: "BPH drugs",
      TypeofDrug: "Alpha-blockers",
      medication: "Tamsulosin",
      dose: "400 micrograms OD after same meal.",
    },
    {
      DrugGroup: "OBSTETRICS, GYNAE & URINARY TRACT",
      DrugSubGroup: "BPH drugs",
      TypeofDrug: "Alpha-blockers",
      medication: "Alfuzosin",
      dose: "10 mg MR OD.",
    },
    {
      DrugGroup: "OBSTETRICS, GYNAE & URINARY TRACT",
      DrugSubGroup: "BPH drugs",
      TypeofDrug: "5-alpha-reductase inhibitors",
      medication: "Finasteride",
      dose: "5 mg OD.",
    },
    {
      DrugGroup: "OBSTETRICS, GYNAE & URINARY TRACT",
      DrugSubGroup: "BPH drugs",
      TypeofDrug: "5-alpha-reductase inhibitors",
      medication: "Dutasteride",
      dose: "0.5 mg OD.",
    },
    {
      DrugGroup: "OBSTETRICS, GYNAE & URINARY TRACT",
      DrugSubGroup: "Erectile dysfunction",
      TypeofDrug: "Erectile dysfunction",
      medication: "Sildenafil",
      dose: "50 mg 1 h pre-sex (25–100 mg range).",
    },
    {
      DrugGroup: "OBSTETRICS, GYNAE & URINARY TRACT",
      DrugSubGroup: "Erectile dysfunction",
      TypeofDrug: "Erectile dysfunction",
      medication: "Tadalafil",
      dose: "10–20 mg PRN (max daily) or 2.5–5 mg OD.",
    },
    {
      DrugGroup: "OBSTETRICS, GYNAE & URINARY TRACT",
      DrugSubGroup: "Erectile dysfunction",
      TypeofDrug: "Erectile dysfunction",
      medication: "Vardenafil",
      dose: "similar 5–20 mg PRN.",
    },
    {
      DrugGroup: "OBSTETRICS, GYNAE & URINARY TRACT",
      DrugSubGroup: "Overactive bladder",
      TypeofDrug: "Antimuscarinics",
      medication: "Oxybutynin",
      dose: "2.5–5 mg BD–TDS (up to 20 mg/day); MR 5–10 mg OD.",
    },
    {
      DrugGroup: "OBSTETRICS, GYNAE & URINARY TRACT",
      DrugSubGroup: "Overactive bladder",
      TypeofDrug: "Antimuscarinics",
      medication: "Tolterodine",
      dose: "2 mg BD; MR 4 mg OD.",
    },
    {
      DrugGroup: "OBSTETRICS, GYNAE & URINARY TRACT",
      DrugSubGroup: "Overactive bladder",
      TypeofDrug: "Antimuscarinics",
      medication: "Solifenacin",
      dose: "5–10 mg OD.",
    },
    {
      DrugGroup: "OBSTETRICS, GYNAE & URINARY TRACT",
      DrugSubGroup: "Overactive bladder",
      TypeofDrug: "Antimuscarinics",
      medication: "Darifenacin",
      dose: "OD.",
    },
    {
      DrugGroup: "OBSTETRICS, GYNAE & URINARY TRACT",
      DrugSubGroup: "Overactive bladder",
      TypeofDrug: "Antimuscarinics",
      medication: "Fesoterodine",
      dose: "OD.",
    },
    {
      DrugGroup: "OBSTETRICS, GYNAE & URINARY TRACT",
      DrugSubGroup: "Overactive bladder",
      TypeofDrug: "Antimuscarinics",
      medication: "Propiverine",
      dose: "OD.",
    },
    {
      DrugGroup: "OBSTETRICS, GYNAE & URINARY TRACT",
      DrugSubGroup: "Overactive bladder",
      TypeofDrug: "Beta-3 agonist",
      medication: "Mirabegron",
      dose: "50 mg OD (25 mg in some impairment).",
    },

    // --- MALIGNANT DISEASE & IMMUNOSUPPRESSION ---
    {
      DrugGroup: "MALIGNANT DISEASE & IMMUNOSUPPRESSION",
      DrugSubGroup: "",
      TypeofDrug: "Cytotoxics (classes)",
      medication: "Cyclophosphamide",
      dose: "500–1500 mg/m² IV per cycle.",
    },
    {
      DrugGroup: "MALIGNANT DISEASE & IMMUNOSUPPRESSION",
      DrugSubGroup: "",
      TypeofDrug: "Cytotoxics (classes)",
      medication: "Doxorubicin",
      dose: "50–75 mg/m² IV per cycle.",
    },
    {
      DrugGroup: "MALIGNANT DISEASE & IMMUNOSUPPRESSION",
      DrugSubGroup: "",
      TypeofDrug: "Targeted TKIs",
      medication: "Imatinib",
      dose: "400–800 mg OD.",
    },
    {
      DrugGroup: "MALIGNANT DISEASE & IMMUNOSUPPRESSION",
      DrugSubGroup: "",
      TypeofDrug: "Targeted TKIs",
      medication: "Erlotinib",
      dose: "150 mg OD.",
    },
    {
      DrugGroup: "MALIGNANT DISEASE & IMMUNOSUPPRESSION",
      DrugSubGroup: "",
      TypeofDrug: "Targeted TKIs",
      medication: "Gefitinib",
      dose: "250 mg OD.",
    },
    {
      DrugGroup: "MALIGNANT DISEASE & IMMUNOSUPPRESSION",
      DrugSubGroup: "",
      TypeofDrug: "Targeted TKIs",
      medication: "Sunitinib",
      dose: "50 mg OD 4 weeks on/2 weeks off.",
    },
    {
      DrugGroup: "MALIGNANT DISEASE & IMMUNOSUPPRESSION",
      DrugSubGroup: "",
      TypeofDrug: "PARP inhibitors",
      medication: "Olaparib",
      dose: "300 mg BD.",
    },
    {
      DrugGroup: "MALIGNANT DISEASE & IMMUNOSUPPRESSION",
      DrugSubGroup: "",
      TypeofDrug: "Hormonal anticancers",
      medication: "Tamoxifen",
      dose: "20 mg OD.",
    },
    {
      DrugGroup: "MALIGNANT DISEASE & IMMUNOSUPPRESSION",
      DrugSubGroup: "",
      TypeofDrug: "Hormonal anticancers",
      medication: "Anastrozole",
      dose: "1 mg OD.",
    },
    {
      DrugGroup: "MALIGNANT DISEASE & IMMUNOSUPPRESSION",
      DrugSubGroup: "",
      TypeofDrug: "Hormonal anticancers",
      medication: "Letrozole",
      dose: "2.5 mg OD.",
    },
    {
      DrugGroup: "MALIGNANT DISEASE & IMMUNOSUPPRESSION",
      DrugSubGroup: "",
      TypeofDrug: "Hormonal anticancers",
      medication: "Exemestane",
      dose: "25 mg OD.",
    },
    {
      DrugGroup: "MALIGNANT DISEASE & IMMUNOSUPPRESSION",
      DrugSubGroup: "",
      TypeofDrug: "Hormonal anticancers",
      medication: "Bicalutamide",
      dose: "50 mg OD (150 mg OD some regimens).",
    },
    {
      DrugGroup: "MALIGNANT DISEASE & IMMUNOSUPPRESSION",
      DrugSubGroup: "",
      TypeofDrug: "Immunosuppressants",
      medication: "Ciclosporin",
      dose: "3–15 mg/kg/day in 2 doses.",
    },
    {
      DrugGroup: "MALIGNANT DISEASE & IMMUNOSUPPRESSION",
      DrugSubGroup: "",
      TypeofDrug: "Immunosuppressants",
      medication: "Tacrolimus",
      dose: "0.05–0.2 mg/kg/day in 2 doses.",
    },
    {
      DrugGroup: "MALIGNANT DISEASE & IMMUNOSUPPRESSION",
      DrugSubGroup: "",
      TypeofDrug: "Immunosuppressants",
      medication: "Azathioprine",
      dose: "1.5–2.5 mg/kg OD.",
    },
    {
      DrugGroup: "MALIGNANT DISEASE & IMMUNOSUPPRESSION",
      DrugSubGroup: "",
      TypeofDrug: "Immunosuppressants",
      medication: "Mycophenolate mofetil",
      dose: "1–1.5 g BD.",
    },
    {
      DrugGroup: "MALIGNANT DISEASE & IMMUNOSUPPRESSION",
      DrugSubGroup: "",
      TypeofDrug: "Immunosuppressants",
      medication: "Methotrexate",
      dose: "7.5–25 mg once weekly.",
    },

    // --- NUTRITION & BLOOD ---
    {
      DrugGroup: "NUTRITION & BLOOD",
      DrugSubGroup: "",
      TypeofDrug: "NUTRITION & BLOOD",
      medication: "Thiamine",
      dose: "100 mg PO OD (deficiency).",
    },
    {
      DrugGroup: "NUTRITION & BLOOD",
      DrugSubGroup: "",
      TypeofDrug: "NUTRITION & BLOOD",
      medication: "Folic acid",
      dose: "5 mg PO OD.",
    },
    {
      DrugGroup: "NUTRITION & BLOOD",
      DrugSubGroup: "",
      TypeofDrug: "NUTRITION & BLOOD",
      medication: "Vitamin D",
      dose: "loading 20,000–50,000 IU weekly; maintenance 800–2000 IU OD.",
    },
    {
      DrugGroup: "NUTRITION & BLOOD",
      DrugSubGroup: "",
      TypeofDrug: "NUTRITION & BLOOD",
      medication: "Ferrous sulfate",
      dose: "200 mg PO BD–TDS.",
    },
    {
      DrugGroup: "NUTRITION & BLOOD",
      DrugSubGroup: "",
      TypeofDrug: "NUTRITION & BLOOD",
      medication: "Ferrous fumarate",
      dose: "210 mg PO BD.",
    },
    {
      DrugGroup: "NUTRITION & BLOOD",
      DrugSubGroup: "",
      TypeofDrug: "NUTRITION & BLOOD",
      medication: "Epoetin",
      dose: "dose weight/Hb based, weekly–monthly.",
    },
    {
      DrugGroup: "NUTRITION & BLOOD",
      DrugSubGroup: "",
      TypeofDrug: "NUTRITION & BLOOD",
      medication: "Desmopressin",
      dose: "0.3 micrograms/kg IV/SC/IN.",
    },
    {
      DrugGroup: "NUTRITION & BLOOD",
      DrugSubGroup: "",
      TypeofDrug: "NUTRITION & BLOOD",
      medication: "PN regimens",
      dose: "ml/kg/day per protocol.",
    },

    // --- EMERGENCY MEDICINES / TOXICOLOGY ---
    {
      DrugGroup: "EMERGENCY MEDICINES / TOXICOLOGY",
      DrugSubGroup: "",
      TypeofDrug: "EMERGENCY MEDICINES / TOXICOLOGY",
      medication: "Naloxone",
      dose: "400 micrograms IV/IM/SC, repeat to effect.",
    },
    {
      DrugGroup: "EMERGENCY MEDICINES / TOXICOLOGY",
      DrugSubGroup: "",
      TypeofDrug: "EMERGENCY MEDICINES / TOXICOLOGY",
      medication: "Flumazenil",
      dose: "200 micrograms IV then 100 micrograms q60s to 1 mg.",
    },
    {
      DrugGroup: "EMERGENCY MEDICINES / TOXICOLOGY",
      DrugSubGroup: "",
      TypeofDrug: "EMERGENCY MEDICINES / TOXICOLOGY",
      medication: "Atropine",
      dose: "500 micrograms IV, repeat to 3 mg (higher in poisoning).",
    },
    {
      DrugGroup: "EMERGENCY MEDICINES / TOXICOLOGY",
      DrugSubGroup: "",
      TypeofDrug: "EMERGENCY MEDICINES / TOXICOLOGY",
      medication: "Activated charcoal",
      dose: "50 g PO/NG once.",
    },
    {
      DrugGroup: "EMERGENCY MEDICINES / TOXICOLOGY",
      DrugSubGroup: "",
      TypeofDrug: "EMERGENCY MEDICINES / TOXICOLOGY",
      medication: "Desferrioxamine",
      dose: "mg/kg IV/IM (iron poisoning, protocol).",
    },
    {
      DrugGroup: "EMERGENCY MEDICINES / TOXICOLOGY",
      DrugSubGroup: "",
      TypeofDrug: "EMERGENCY MEDICINES / TOXICOLOGY",
      medication: "EDTA",
      dose: "mg/kg IV (lead, etc., protocol).",
    },
    {
      DrugGroup: "EMERGENCY MEDICINES / TOXICOLOGY",
      DrugSubGroup: "",
      TypeofDrug: "EMERGENCY MEDICINES / TOXICOLOGY",
      medication: "Dimercaprol",
      dose: "mg/kg IM (arsenic, etc., protocol).",
    },
    {
      DrugGroup: "EMERGENCY MEDICINES / TOXICOLOGY",
      DrugSubGroup: "",
      TypeofDrug: "EMERGENCY MEDICINES / TOXICOLOGY",
      medication: "Adrenaline 1:1000",
      dose: "500 micrograms IM for anaphylaxis, repeat q5min.",
    },
    {
      DrugGroup: "EMERGENCY MEDICINES / TOXICOLOGY",
      DrugSubGroup: "",
      TypeofDrug: "EMERGENCY MEDICINES / TOXICOLOGY",
      medication: "Chlorphenamine",
      dose: "10 mg IV/IM.",
    },
    {
      DrugGroup: "EMERGENCY MEDICINES / TOXICOLOGY",
      DrugSubGroup: "",
      TypeofDrug: "EMERGENCY MEDICINES / TOXICOLOGY",
      medication: "Hydrocortisone",
      dose: "200 mg IV.",
    },

    //Missing
    {
      DrugGroup: "GASTROINTESTINAL SYSTEM",
      DrugSubGroup: "Dyspepsia & GORD",
      TypeofDrug: "H2-receptor antagonists",
      medication: "Cimetidine",
      dose: "400 mg BD or 800 mg ON (less used, interactions).",
    },
    {
      DrugGroup: "GASTROINTESTINAL SYSTEM",
      DrugSubGroup: "Antiemetics",
      TypeofDrug: "5-HT3 antagonists",
      medication: "Granisetron",
      dose: "1–2 mg PO/IV OD.",
    },
    {
      DrugGroup: "GASTROINTESTINAL SYSTEM",
      DrugSubGroup: "Antiemetics",
      TypeofDrug: "5-HT3 antagonists",
      medication: "Palonosetron",
      dose: "0.25 mg IV once before chemo.",
    },
    {
      DrugGroup: "GASTROINTESTINAL SYSTEM",
      DrugSubGroup: "Antiemetics",
      TypeofDrug: "Antihistamines (N&V)",
      medication: "Cinnarizine",
      dose: "30 mg 2–3×/day.",
    },
    {
      DrugGroup: "GASTROINTESTINAL SYSTEM",
      DrugSubGroup: "Antiemetics",
      TypeofDrug: "Anticholinergics",
      medication: "Hyoscine hydrobromide",
      dose: "300–600 micrograms PO 30 min pre-travel, then q6h PRN; patch regimens brand-specific.",
    },
    {
      DrugGroup: "GASTROINTESTINAL SYSTEM",
      DrugSubGroup: "Antiemetics",
      TypeofDrug: "NK1 antagonists",
      medication: "Aprepitant",
      dose: "125 mg PO day 1, then 80 mg OD days 2–3 (CINV).",
    },
    {
      DrugGroup: "GASTROINTESTINAL SYSTEM",
      DrugSubGroup: "Antiemetics",
      TypeofDrug: "NK1 antagonists",
      medication: "Fosaprepitant",
      dose: "150 mg IV once pre-chemo.",
    },
    {
      DrugGroup: "GASTROINTESTINAL SYSTEM",
      DrugSubGroup: "Disorders of Bowel Motility",
      TypeofDrug: "Antidiarrhoeals",
      medication: "Codeine",
      dose: "30 mg TDS–QDS (less used).",
    },
    {
      DrugGroup: "GASTROINTESTINAL SYSTEM",
      DrugSubGroup: "Disorders of Bowel Motility",
      TypeofDrug: "Antidiarrhoeals",
      medication: "Racecadotril",
      dose: "100 mg TDS before meals (where used).",
    },
    {
      DrugGroup: "GASTROINTESTINAL SYSTEM",
      DrugSubGroup: "Disorders of Bowel Motility",
      TypeofDrug: "Prokinetics",
      medication: "Metoclopramide",
      dose: "100 mg TDS before meals (where used).",
    },
    {
      DrugGroup: "GASTROINTESTINAL SYSTEM",
      DrugSubGroup: "Disorders of Bowel Motility",
      TypeofDrug: "Prokinetics",
      medication: "Domperidone",
      dose: "100 mg TDS before meals (where used).",
    },
    {
      DrugGroup: "GASTROINTESTINAL SYSTEM",
      DrugSubGroup: "Disorders of Bowel Motility",
      TypeofDrug: "Prokinetics",
      medication: "Erythromycin",
      dose: "250 mg TDS (short-term for gastroparesis).",
    },
    {
      DrugGroup: "GASTROINTESTINAL SYSTEM",
      DrugSubGroup: "Inflammatory Bowel Disease",
      TypeofDrug: "Aminosalicylates",
      medication: "Sulfasalazine",
      dose: "500 mg QID up to 2–4 g/day.",
    },
    {
      DrugGroup: "GASTROINTESTINAL SYSTEM",
      DrugSubGroup: "Inflammatory Bowel Disease",
      TypeofDrug: "Corticosteroids (IBD)",
      medication: "Budesonide (MR)",
      dose: "9 mg OD then taper.",
    },
    {
      DrugGroup: "GASTROINTESTINAL SYSTEM",
      DrugSubGroup: "Inflammatory Bowel Disease",
      TypeofDrug: "Immunomodulators",
      medication: "Azathioprine",
      dose: "2–2.5 mg/kg OD (TPMT-guided).",
    },
    {
      DrugGroup: "GASTROINTESTINAL SYSTEM",
      DrugSubGroup: "Inflammatory Bowel Disease",
      TypeofDrug: "Immunomodulators",
      medication: "6-Mercaptopurine",
      dose: "1–1.5 mg/kg OD.",
    },
    {
      DrugGroup: "GASTROINTESTINAL SYSTEM",
      DrugSubGroup: "Inflammatory Bowel Disease",
      TypeofDrug: "Immunomodulators",
      medication: "Methotrexate",
      dose: "15–25 mg once weekly + folic acid.",
    },
    {
      DrugGroup: "GASTROINTESTINAL SYSTEM",
      DrugSubGroup: "Inflammatory Bowel Disease",
      TypeofDrug: "Biologics (examples)",
      medication: "Infliximab",
      dose: "5 mg/kg IV weeks 0,2,6 then q8w.",
    },
    {
      DrugGroup: "GASTROINTESTINAL SYSTEM",
      DrugSubGroup: "Inflammatory Bowel Disease",
      TypeofDrug: "Biologics (examples)",
      medication: "Adalimumab",
      dose: "160 mg SC wk 0, 80 mg wk 2, then 40 mg q2w.",
    },
    {
      DrugGroup: "GASTROINTESTINAL SYSTEM",
      DrugSubGroup: "Inflammatory Bowel Disease",
      TypeofDrug: "Biologics (examples)",
      medication: "Vedolizumab",
      dose: "fixed loading & maintenance regimens.",
    },
    {
      DrugGroup: "GASTROINTESTINAL SYSTEM",
      DrugSubGroup: "Inflammatory Bowel Disease",
      TypeofDrug: "Biologics (examples)",
      medication: "Ustekinumab",
      dose: "fixed loading & maintenance regimens.",
    },
    {
      DrugGroup: "GASTROINTESTINAL SYSTEM",
      DrugSubGroup: "Liver disease drugs",
      TypeofDrug: "Liver disease drugs",
      medication: "Lactulose (encephalopathy)",
      dose: "15–45 mL 2–4×/day to 2–3 soft stools/day.",
    },
    {
      DrugGroup: "GASTROINTESTINAL SYSTEM",
      DrugSubGroup: "Liver disease drugs",
      TypeofDrug: "Liver disease drugs",
      medication: "Rifaximin",
      dose: "550 mg BD.",
    },
    {
      DrugGroup: "GASTROINTESTINAL SYSTEM",
      DrugSubGroup: "Pancreatic replacement therapy",
      TypeofDrug: "Pancreatic replacement therapy",
      medication: "Pancreatin",
      dose: "typically 25,000–50,000 units lipase with meals, 10,000–25,000 with snacks, titrated to symptoms/fat intake.",
    },

    // --- CARDIOVASCULAR SYSTEM (Missing Items) ---
    {
      DrugGroup: "CARDIOVASCULAR SYSTEM",
      DrugSubGroup: "Diuretics",
      TypeofDrug: "Thiazide / thiazide-like",
      medication: "Hydrochlorothiazide",
      dose: "12.5–25 mg OD.",
    },
    {
      DrugGroup: "CARDIOVASCULAR SYSTEM",
      DrugSubGroup: "Diuretics",
      TypeofDrug: "Potassium-sparing",
      medication: "Eplerenone",
      dose: "25 mg OD → 50 mg OD/BD.",
    },
    {
      DrugGroup: "CARDIOVASCULAR SYSTEM",
      DrugSubGroup: "Diuretics",
      TypeofDrug: "Potassium-sparing",
      medication: "Amiloride",
      dose: "5–10 mg OD (often combo).",
    },
    {
      DrugGroup: "CARDIOVASCULAR SYSTEM",
      DrugSubGroup: "Diuretics",
      TypeofDrug: "Osmotic",
      medication: "Mannitol",
      dose: "0.25–1 g/kg IV over 30–60 min (raised ICP etc.).",
    },
    {
      DrugGroup: "CARDIOVASCULAR SYSTEM",
      DrugSubGroup: "Beta-blockers",
      TypeofDrug: "Beta-blockers",
      medication: "Metoprolol",
      dose: "50–100 mg/day (divided or MR), titrate up.",
    },
    {
      DrugGroup: "CARDIOVASCULAR SYSTEM",
      DrugSubGroup: "Beta-blockers",
      TypeofDrug: "Beta-blockers",
      medication: "Nebivolol",
      dose: "5 mg OD (2.5–10 mg range).",
    },
    {
      DrugGroup: "CARDIOVASCULAR SYSTEM",
      DrugSubGroup: "Vasodilators",
      TypeofDrug: "Nitrates",
      medication: "Isosorbide dinitrate",
      dose: "20–40 mg 2–3×/day (IV protocols exist).",
    },
    {
      DrugGroup: "CARDIOVASCULAR SYSTEM",
      DrugSubGroup: "Vasodilators",
      TypeofDrug: "Vasodilators",
      medication: "Hydralazine",
      dose: "25 mg BD → 50–75 mg QDS.",
    },
    {
      DrugGroup: "CARDIOVASCULAR SYSTEM",
      DrugSubGroup: "Vasodilators",
      TypeofDrug: "Vasodilators",
      medication: "Minoxidil",
      dose: "5–10 mg OD, titrate up under specialist care (up to ~100 mg/day).",
    },
    {
      DrugGroup: "CARDIOVASCULAR SYSTEM",
      DrugSubGroup: "Calcium-channel blockers",
      TypeofDrug: "Calcium-channel blockers",
      medication: "Verapamil",
      dose: "120–480 mg/day in divided/MR doses.",
    },
    {
      DrugGroup: "CARDIOVASCULAR SYSTEM",
      DrugSubGroup: "ACE inhibitors",
      TypeofDrug: "ACE inhibitors",
      medication: "Perindopril",
      dose: "2–4 mg OD → 8 mg OD.",
    },
    {
      DrugGroup: "CARDIOVASCULAR SYSTEM",
      DrugSubGroup: "ARBs",
      TypeofDrug: "ARBs",
      medication: "Telmisartan",
      dose: "40–80 mg OD.",
    },
    {
      DrugGroup: "CARDIOVASCULAR SYSTEM",
      DrugSubGroup: "Renin inhibitors",
      TypeofDrug: "Renin inhibitors",
      medication: "Aliskiren",
      dose: "150 mg OD → 300 mg OD.",
    },
    {
      DrugGroup: "CARDIOVASCULAR SYSTEM",
      DrugSubGroup: "Heart failure medications",
      TypeofDrug: "Heart failure medications",
      medication: "Empagliflozin",
      dose: "10 mg OD (up to 25 mg OD some indications).",
    },
    {
      DrugGroup: "CARDIOVASCULAR SYSTEM",
      DrugSubGroup: "Antiarrhythmics",
      TypeofDrug: "Class I",
      medication: "Flecainide",
      dose: "50–100 mg BD (max ~300 mg/day), specialist.",
    },
    {
      DrugGroup: "CARDIOVASCULAR SYSTEM",
      DrugSubGroup: "Antiarrhythmics",
      TypeofDrug: "Others",
      medication: "Adenosine",
      dose: "6 mg rapid IV bolus → if no response 12 mg → may repeat 12 mg.",
    },
    {
      DrugGroup: "CARDIOVASCULAR SYSTEM",
      DrugSubGroup: "Anticoagulants",
      TypeofDrug: "Heparins",
      medication: "UFH",
      dose: "5000 units IV bolus then infusion titrated to APTT.",
    },
    {
      DrugGroup: "CARDIOVASCULAR SYSTEM",
      DrugSubGroup: "Anticoagulants",
      TypeofDrug: "DOACs",
      medication: "Edoxaban",
      dose: "60 mg OD (dose reduce in some).",
    },
    {
      DrugGroup: "CARDIOVASCULAR SYSTEM",
      DrugSubGroup: "Anticoagulants",
      TypeofDrug: "DOACs",
      medication: "Dabigatran",
      dose: "150 mg BD (110 mg BD in some).",
    },
    {
      DrugGroup: "CARDIOVASCULAR SYSTEM",
      DrugSubGroup: "Antiplatelets",
      TypeofDrug: "Antiplatelets",
      medication: "Prasugrel",
      dose: "10 mg OD (5 mg OD some pts; LD 60 mg).",
    },
    {
      DrugGroup: "CARDIOVASCULAR SYSTEM",
      DrugSubGroup: "Antiplatelets",
      TypeofDrug: "Antiplatelets",
      medication: "Ticagrelor",
      dose: "90 mg BD after LD 180 mg.",
    },
    {
      DrugGroup: "CARDIOVASCULAR SYSTEM",
      DrugSubGroup: "Antiplatelets",
      TypeofDrug: "GP IIb/IIIa inhibitors",
      medication: "GP IIb/IIIa inhibitors",
      dose: "weight-based IV in cath/PCI protocols.",
    },
    {
      DrugGroup: "CARDIOVASCULAR SYSTEM",
      DrugSubGroup: "Lipid-lowering agents",
      TypeofDrug: "Lipid-lowering agents",
      medication: "Ezetimibe",
      dose: "10 mg OD.",
    },
    {
      DrugGroup: "CARDIOVASCULAR SYSTEM",
      DrugSubGroup: "Lipid-lowering agents",
      TypeofDrug: "PCSK9 inhibitors",
      medication: "Alirocumab",
      dose: "75–150 mg SC q2w or 300 mg q4w.",
    },
    {
      DrugGroup: "CARDIOVASCULAR SYSTEM",
      DrugSubGroup: "Lipid-lowering agents",
      TypeofDrug: "PCSK9 inhibitors",
      medication: "Evolocumab",
      dose: "140 mg SC q2w or 420 mg q4w.",
    },

    // --- RESPIRATORY SYSTEM (Missing Items) ---
    {
      DrugGroup: "RESPIRATORY SYSTEM",
      DrugSubGroup: "",
      TypeofDrug: "SABA",
      medication: "Terbutaline",
      dose: "0.5–1 mg via inhaler up to QID.",
    },
    {
      DrugGroup: "RESPIRATORY SYSTEM",
      DrugSubGroup: "",
      TypeofDrug: "LABA",
      medication: "Formoterol",
      dose: "12–24 micrograms BD.",
    },
    {
      DrugGroup: "RESPIRATORY SYSTEM",
      DrugSubGroup: "",
      TypeofDrug: "ICS",
      medication: "Fluticasone propionate",
      dose: "100–250 micrograms BD (up to higher in severe).",
    },
    {
      DrugGroup: "RESPIRATORY SYSTEM",
      DrugSubGroup: "",
      TypeofDrug: "LABA/ICS combos",
      medication: "Formoterol/Budesonide",
      dose: "160/4.5 micrograms 1–2 puffs BD.",
    },
    {
      DrugGroup: "RESPIRATORY SYSTEM",
      DrugSubGroup: "",
      TypeofDrug: "LAMA",
      medication: "Glycopyrronium",
      dose: "once or twice daily depending on product.",
    },
    {
      DrugGroup: "RESPIRATORY SYSTEM",
      DrugSubGroup: "",
      TypeofDrug: "LAMA",
      medication: "Aclidinium",
      dose: "once or twice daily depending on product.",
    },
    {
      DrugGroup: "RESPIRATORY SYSTEM",
      DrugSubGroup: "",
      TypeofDrug: "LAMA",
      medication: "Umeclidinium",
      dose: "once or twice daily depending on product.",
    },
    {
      DrugGroup: "RESPIRATORY SYSTEM",
      DrugSubGroup: "",
      TypeofDrug: "Theophyllines",
      medication: "MR theophylline",
      dose: "~200–400 mg BD, level-guided.",
    },
    {
      DrugGroup: "RESPIRATORY SYSTEM",
      DrugSubGroup: "",
      TypeofDrug: "Biologics (asthma, etc.)",
      medication: "Omalizumab",
      dose: "SC dose based on weight & IgE, q2–4w.",
    },
    {
      DrugGroup: "RESPIRATORY SYSTEM",
      DrugSubGroup: "",
      TypeofDrug: "Biologics (asthma, etc.)",
      medication: "Mepolizumab",
      dose: "fixed SC doses q4w.",
    },
    {
      DrugGroup: "RESPIRATORY SYSTEM",
      DrugSubGroup: "",
      TypeofDrug: "Biologics (asthma, etc.)",
      medication: "Benralizumab",
      dose: "fixed SC doses q4–8w.",
    },
    {
      DrugGroup: "RESPIRATORY SYSTEM",
      DrugSubGroup: "",
      TypeofDrug: "Biologics (asthma, etc.)",
      medication: "Dupilumab",
      dose: "fixed SC doses q2w or q4w depending on agent.",
    },

    // --- CNS (Missing Items) ---
    {
      DrugGroup: "CNS",
      DrugSubGroup: "Hypnotics & anxiolytics",
      TypeofDrug: "Benzodiazepines",
      medication: "Temazepam",
      dose: "10–20 mg ON (short-term).",
    },
    {
      DrugGroup: "CNS",
      DrugSubGroup: "Hypnotics & anxiolytics",
      TypeofDrug: "Z-drugs",
      medication: "Zolpidem",
      dose: "5–10 mg ON.",
    },
    {
      DrugGroup: "CNS",
      DrugSubGroup: "Hypnotics & anxiolytics",
      TypeofDrug: "Buspirone",
      medication: "Buspirone",
      dose: "5 mg BD–TDS initially → 20–30 mg/day (max 60 mg) in divided doses.",
    },
    {
      DrugGroup: "CNS",
      DrugSubGroup: "Antipsychotics",
      TypeofDrug: "Typical",
      medication: "Chlorpromazine",
      dose: "25–100 mg TDS (higher in psychosis, SE-limited).",
    },
    {
      DrugGroup: "CNS",
      DrugSubGroup: "Antipsychotics",
      TypeofDrug: "Atypical",
      medication: "Clozapine",
      dose: "start 12.5 mg OD/BD → 300–450 mg/day (specialist monitoring).",
    },
    {
      DrugGroup: "CNS",
      DrugSubGroup: "Antipsychotics",
      TypeofDrug: "Atypical",
      medication: "Aripiprazole",
      dose: "10–30 mg OD.",
    },
    {
      DrugGroup: "CNS",
      DrugSubGroup: "Antidepressants",
      TypeofDrug: "SSRIs",
      medication: "Escitalopram",
      dose: "10 mg OD → 20 mg OD.",
    },
    {
      DrugGroup: "CNS",
      DrugSubGroup: "Antidepressants",
      TypeofDrug: "SSRIs",
      medication: "Paroxetine",
      dose: "20 mg OD → up to 50–60 mg/day.",
    },
    {
      DrugGroup: "CNS",
      DrugSubGroup: "Antidepressants",
      TypeofDrug: "SNRIs",
      medication: "Duloxetine",
      dose: "30–60 mg OD → up to 120 mg/day.",
    },
    {
      DrugGroup: "CNS",
      DrugSubGroup: "Antidepressants",
      TypeofDrug: "MAOIs",
      medication: "Phenelzine",
      dose: "15 mg TDS → up to 90 mg/day.",
    },
    {
      DrugGroup: "CNS",
      DrugSubGroup: "Antidepressants",
      TypeofDrug: "Atypical antidepressants",
      medication: "Trazodone",
      dose: "150–300 mg/day (or 50–100 mg ON for sleep).",
    },
    {
      DrugGroup: "CNS",
      DrugSubGroup: "Antidepressants",
      TypeofDrug: "Atypical antidepressants",
      medication: "Bupropion",
      dose: "150–300 mg/day (varies by formulation).",
    },
    {
      DrugGroup: "CNS",
      DrugSubGroup: "Bipolar drugs",
      TypeofDrug: "Bipolar drugs",
      medication: "Lamotrigine",
      dose: "25 mg OD → 100–200 mg/day (slow titration).",
    },
    {
      DrugGroup: "CNS",
      DrugSubGroup: "CNS stimulants & ADHD",
      TypeofDrug: "CNS stimulants & ADHD",
      medication: "Methylphenidate",
      dose: "start 5–10 mg 1–2×/day → 20–60 mg/day (or MR equivalent).",
    },
    {
      DrugGroup: "CNS",
      DrugSubGroup: "CNS stimulants & ADHD",
      TypeofDrug: "CNS stimulants & ADHD",
      medication: "Lisdexamfetamine",
      dose: "30 mg OD → up to 70 mg OD.",
    },
    {
      DrugGroup: "CNS",
      DrugSubGroup: "CNS stimulants & ADHD",
      TypeofDrug: "CNS stimulants & ADHD",
      medication: "Atomoxetine",
      dose: "~40–100 mg/day (0.5–1.4 mg/kg/day).",
    },
    {
      DrugGroup: "CNS",
      DrugSubGroup: "Antiepileptics",
      TypeofDrug: "Antiepileptics",
      medication: "Lamotrigine",
      dose: "100–500 mg/day.",
    },
    {
      DrugGroup: "CNS",
      DrugSubGroup: "Antiepileptics",
      TypeofDrug: "Antiepileptics",
      medication: "Carbamazepine",
      dose: "400–1200 mg/day.",
    },
    {
      DrugGroup: "CNS",
      DrugSubGroup: "Antiepileptics",
      TypeofDrug: "Antiepileptics",
      medication: "Topiramate",
      dose: "agent-specific titration.",
    },
    {
      DrugGroup: "CNS",
      DrugSubGroup: "Antiepileptics",
      TypeofDrug: "Antiepileptics",
      medication: "Lacosamide",
      dose: "agent-specific titration.",
    },
    {
      DrugGroup: "CNS",
      DrugSubGroup: "Antiepileptics",
      TypeofDrug: "Antiepileptics",
      medication: "Phenytoin",
      dose: "agent-specific titration.",
    },
    {
      DrugGroup: "CNS",
      DrugSubGroup: "Parkinson’s",
      TypeofDrug: "Parkinson’s",
      medication: "Pramipexole",
      dose: "start low, titrate up by schedules.",
    },
    {
      DrugGroup: "CNS",
      DrugSubGroup: "Parkinson’s",
      TypeofDrug: "Parkinson’s",
      medication: "Ropinirole",
      dose: "start low, titrate up by schedules.",
    },
    {
      DrugGroup: "CNS",
      DrugSubGroup: "Parkinson’s",
      TypeofDrug: "Parkinson’s",
      medication: "Rotigotine",
      dose: "start low, titrate up by schedules.",
    },
    {
      DrugGroup: "CNS",
      DrugSubGroup: "Parkinson’s",
      TypeofDrug: "Parkinson’s",
      medication: "Selegiline",
      dose: "OD dosing.",
    },
    {
      DrugGroup: "CNS",
      DrugSubGroup: "Parkinson’s",
      TypeofDrug: "Parkinson’s",
      medication: "Rasagiline",
      dose: "OD dosing.",
    },
    {
      DrugGroup: "CNS",
      DrugSubGroup: "Parkinson’s",
      TypeofDrug: "Parkinson’s",
      medication: "Safinamide",
      dose: "OD dosing.",
    },
    {
      DrugGroup: "CNS",
      DrugSubGroup: "Parkinson’s",
      TypeofDrug: "Parkinson’s",
      medication: "Entacapone",
      dose: "adjunct doses with levodopa.",
    },
    {
      DrugGroup: "CNS",
      DrugSubGroup: "Parkinson’s",
      TypeofDrug: "Parkinson’s",
      medication: "Opicapone",
      dose: "adjunct doses with levodopa.",
    },
    {
      DrugGroup: "CNS",
      DrugSubGroup: "Dementia",
      TypeofDrug: "Dementia",
      medication: "Donepezil",
      dose: "5 mg ON → 10 mg ON.",
    },
    {
      DrugGroup: "CNS",
      DrugSubGroup: "Dementia",
      TypeofDrug: "Dementia",
      medication: "Rivastigmine",
      dose: "1.5 mg BD → 6 mg BD, or patch (4.6–13.3 mg/24 h).",
    },
    {
      DrugGroup: "CNS",
      DrugSubGroup: "Dementia",
      TypeofDrug: "Dementia",
      medication: "Galantamine",
      dose: "8–24 mg/day.",
    },
    {
      DrugGroup: "CNS",
      DrugSubGroup: "Dementia",
      TypeofDrug: "Dementia",
      medication: "Memantine",
      dose: "5 mg OD → 20 mg OD.",
    },

    // --- INFECTIONS / ANTIMICROBIALS (Missing Items) ---
    {
      DrugGroup: "INFECTIONS / ANTIMICROBIALS",
      DrugSubGroup: "Antibiotics",
      TypeofDrug: "Penicillins",
      medication: "Penicillin V",
      dose: "250–500 mg every 6 hours.",
    },
    {
      DrugGroup: "INFECTIONS / ANTIMICROBIALS",
      DrugSubGroup: "Antibiotics",
      TypeofDrug: "Penicillins",
      medication: "Benzylpenicillin",
      dose: "1.2–2.4 g IV every 4–6 hours.",
    },
    {
      DrugGroup: "INFECTIONS / ANTIMICROBIALS",
      DrugSubGroup: "Antibiotics",
      TypeofDrug: "Penicillins",
      medication: "Ampicillin",
      dose: "500 mg 6-hourly PO (IV regimens vary).",
    },
    {
      DrugGroup: "INFECTIONS / ANTIMICROBIALS",
      DrugSubGroup: "Antibiotics",
      TypeofDrug: "Cephalosporins",
      medication: "Cefazolin",
      dose: "1–2 g IV every 8 hours.",
    },
    {
      DrugGroup: "INFECTIONS / ANTIMICROBIALS",
      DrugSubGroup: "Antibiotics",
      TypeofDrug: "Cephalosporins",
      medication: "Cefuroxime axetil",
      dose: "250–500 mg BD.",
    },
    {
      DrugGroup: "INFECTIONS / ANTIMICROBIALS",
      DrugSubGroup: "Antibiotics",
      TypeofDrug: "Cephalosporins",
      medication: "Cefuroxime",
      dose: "750 mg–1.5 g IV every 8 hours.",
    },
    {
      DrugGroup: "INFECTIONS / ANTIMICROBIALS",
      DrugSubGroup: "Antibiotics",
      TypeofDrug: "Cephalosporins",
      medication: "Cefotaxime",
      dose: "1–2 g every 6–8 hours.",
    },
    {
      DrugGroup: "INFECTIONS / ANTIMICROBIALS",
      DrugSubGroup: "Antibiotics",
      TypeofDrug: "Cephalosporins",
      medication: "Ceftazidime",
      dose: "1–2 g every 8–12 hours.",
    },
    {
      DrugGroup: "INFECTIONS / ANTIMICROBIALS",
      DrugSubGroup: "Antibiotics",
      TypeofDrug: "Cephalosporins",
      medication: "Cefepime",
      dose: "1–2 g every 8–12 hours IV.",
    },
    {
      DrugGroup: "INFECTIONS / ANTIMICROBIALS",
      DrugSubGroup: "Antibiotics",
      TypeofDrug: "Cephalosporins",
      medication: "Ceftaroline",
      dose: "600 mg IV every 12 hours.",
    },
    {
      DrugGroup: "INFECTIONS / ANTIMICROBIALS",
      DrugSubGroup: "Antibiotics",
      TypeofDrug: "Cephalosporins",
      medication: "Ceftobiprole",
      dose: "500 mg IV every 8 hours.",
    },
    {
      DrugGroup: "INFECTIONS / ANTIMICROBIALS",
      DrugSubGroup: "Antibiotics",
      TypeofDrug: "Carbapenems",
      medication: "Meropenem",
      dose: "500 mg–1 g every 8 hours.",
    },
    {
      DrugGroup: "INFECTIONS / ANTIMICROBIALS",
      DrugSubGroup: "Antibiotics",
      TypeofDrug: "Carbapenems",
      medication: "Imipenem/cilastatin",
      dose: "500 mg every 6 hours or 1 g every 8 hours.",
    },
    {
      DrugGroup: "INFECTIONS / ANTIMICROBIALS",
      DrugSubGroup: "Antibiotics",
      TypeofDrug: "Carbapenems",
      medication: "Ertapenem",
      dose: "1 g OD.",
    },
    {
      DrugGroup: "INFECTIONS / ANTIMICROBIALS",
      DrugSubGroup: "Antibiotics",
      TypeofDrug: "Carbapenems",
      medication: "Doripenem",
      dose: "500 mg every 8 hours.",
    },
    {
      DrugGroup: "INFECTIONS / ANTIMICROBIALS",
      DrugSubGroup: "Antibiotics",
      TypeofDrug: "Monobactams",
      medication: "Aztreonam",
      dose: "1–2 g IV every 6–8 hours.",
    },
    {
      DrugGroup: "INFECTIONS / ANTIMICROBIALS",
      DrugSubGroup: "Antibiotics",
      TypeofDrug: "Macrolides",
      medication: "Erythromycin",
      dose: "250–500 mg QID.",
    },
    {
      DrugGroup: "INFECTIONS / ANTIMICROBIALS",
      DrugSubGroup: "Antibiotics",
      TypeofDrug: "Tetracyclines",
      medication: "Tetracycline",
      dose: "250–500 mg QID.",
    },
    {
      DrugGroup: "INFECTIONS / ANTIMICROBIALS",
      DrugSubGroup: "Antibiotics",
      TypeofDrug: "Tetracyclines",
      medication: "Minocycline",
      dose: "100 mg OD or BD.",
    },
    {
      DrugGroup: "INFECTIONS / ANTIMICROBIALS",
      DrugSubGroup: "Antibiotics",
      TypeofDrug: "Aminoglycosides",
      medication: "Amikacin",
      dose: "15 mg/kg IV OD.",
    },
    {
      DrugGroup: "INFECTIONS / ANTIMICROBIALS",
      DrugSubGroup: "Antibiotics",
      TypeofDrug: "Aminoglycosides",
      medication: "Tobramycin",
      dose: "4–7 mg/kg IV OD.",
    },
    {
      DrugGroup: "INFECTIONS / ANTIMICROBIALS",
      DrugSubGroup: "Antibiotics",
      TypeofDrug: "Fluoroquinolones",
      medication: "Moxifloxacin",
      dose: "400 mg OD.",
    },
    {
      DrugGroup: "INFECTIONS / ANTIMICROBIALS",
      DrugSubGroup: "Antibiotics",
      TypeofDrug: "Glycopeptides",
      medication: "Teicoplanin",
      dose: "400–600 mg OD ×3–5 doses, then 200–400 mg OD.",
    },
    {
      DrugGroup: "INFECTIONS / ANTIMICROBIALS",
      DrugSubGroup: "Antibiotics",
      TypeofDrug: "Oxazolidinones",
      medication: "Linezolid",
      dose: "600 mg BD.",
    },
    {
      DrugGroup: "INFECTIONS / ANTIMICROBIALS",
      DrugSubGroup: "Antibiotics",
      TypeofDrug: "Polymyxins",
      medication: "Colistin",
      dose: "specialist dosing (e.g. 9 MIU loading then 4.5 MIU q12h).",
    },
    {
      DrugGroup: "INFECTIONS / ANTIMICROBIALS",
      DrugSubGroup: "Antifungals",
      TypeofDrug: "Azoles",
      medication: "Itraconazole",
      dose: "100–200 mg/day.",
    },
    {
      DrugGroup: "INFECTIONS / ANTIMICROBIALS",
      DrugSubGroup: "Antifungals",
      TypeofDrug: "Azoles",
      medication: "Voriconazole",
      dose: "6 mg/kg IV q12h ×2 → 4 mg/kg q12h.",
    },
    {
      DrugGroup: "INFECTIONS / ANTIMICROBIALS",
      DrugSubGroup: "Antifungals",
      TypeofDrug: "Azoles",
      medication: "Posaconazole",
      dose: "300 mg/day after loading.",
    },
    {
      DrugGroup: "INFECTIONS / ANTIMICROBIALS",
      DrugSubGroup: "Antifungals",
      TypeofDrug: "Echinocandins",
      medication: "Caspofungin",
      dose: "70 mg loading then 50 mg IV OD.",
    },
    {
      DrugGroup: "INFECTIONS / ANTIMICROBIALS",
      DrugSubGroup: "Antifungals",
      TypeofDrug: "Echinocandins",
      medication: "Micafungin",
      dose: "50–100 mg IV OD.",
    },
    {
      DrugGroup: "INFECTIONS / ANTIMICROBIALS",
      DrugSubGroup: "Antifungals",
      TypeofDrug: "Echinocandins",
      medication: "Anidulafungin",
      dose: "200 mg loading then 100 mg IV OD.",
    },
    {
      DrugGroup: "INFECTIONS / ANTIMICROBIALS",
      DrugSubGroup: "Antifungals",
      TypeofDrug: "Polyenes",
      medication: "Amphotericin B (liposomal)",
      dose: "3–5 mg/kg IV OD.",
    },
    {
      DrugGroup: "INFECTIONS / ANTIMICROBIALS",
      DrugSubGroup: "Antifungals",
      TypeofDrug: "Polyenes",
      medication: "Amphotericin B (deoxycholate)",
      dose: "0.7–1 mg/kg/day.",
    },
    {
      DrugGroup: "INFECTIONS / ANTIMICROBIALS",
      DrugSubGroup: "Antifungals",
      TypeofDrug: "Allylamines",
      medication: "Terbinafine",
      dose: "250 mg OD.",
    },
    {
      DrugGroup: "INFECTIONS / ANTIMICROBIALS",
      DrugSubGroup: "Antivirals",
      TypeofDrug: "Influenza antivirals",
      medication: "Oseltamivir",
      dose: "75 mg BD (treatment) or 75 mg OD (prophylaxis).",
    },
    {
      DrugGroup: "INFECTIONS / ANTIMICROBIALS",
      DrugSubGroup: "Antivirals",
      TypeofDrug: "Influenza antivirals",
      medication: "Zanamivir",
      dose: "10 mg inhaled BD ×5 days.",
    },
    {
      DrugGroup: "INFECTIONS / ANTIMICROBIALS",
      DrugSubGroup: "Antivirals",
      TypeofDrug: "Herpes antivirals",
      medication: "Valaciclovir",
      dose: "500 mg–1 g BD–TDS.",
    },
    {
      DrugGroup: "INFECTIONS / ANTIMICROBIALS",
      DrugSubGroup: "Antivirals",
      TypeofDrug: "HIV antivirals",
      medication: "Tenofovir",
      dose: "regimen-based.",
    },
    {
      DrugGroup: "INFECTIONS / ANTIMICROBIALS",
      DrugSubGroup: "Antivirals",
      TypeofDrug: "HIV antivirals",
      medication: "Emtricitabine",
      dose: "regimen-based.",
    },
    {
      DrugGroup: "INFECTIONS / ANTIMICROBIALS",
      DrugSubGroup: "Antivirals",
      TypeofDrug: "HIV antivirals",
      medication: "Lamivudine",
      dose: "regimen-based.",
    },
    {
      DrugGroup: "INFECTIONS / ANTIMICROBIALS",
      DrugSubGroup: "Antivirals",
      TypeofDrug: "HIV antivirals",
      medication: "Abacavir",
      dose: "regimen-based.",
    },
    {
      DrugGroup: "INFECTIONS / ANTIMICROBIALS",
      DrugSubGroup: "Antivirals",
      TypeofDrug: "HIV antivirals",
      medication: "Efavirenz",
      dose: "regimen-based.",
    },
    {
      DrugGroup: "INFECTIONS / ANTIMICROBIALS",
      DrugSubGroup: "Antivirals",
      TypeofDrug: "HIV antivirals",
      medication: "Rilpivirine",
      dose: "regimen-based.",
    },
    {
      DrugGroup: "INFECTIONS / ANTIMICROBIALS",
      DrugSubGroup: "Antivirals",
      TypeofDrug: "HIV antivirals",
      medication: "Atazanavir",
      dose: "regimen-based.",
    },
    {
      DrugGroup: "INFECTIONS / ANTIMICROBIALS",
      DrugSubGroup: "Antivirals",
      TypeofDrug: "HIV antivirals",
      medication: "Darunavir",
      dose: "regimen-based.",
    },
    {
      DrugGroup: "INFECTIONS / ANTIMICROBIALS",
      DrugSubGroup: "Antivirals",
      TypeofDrug: "HIV antivirals",
      medication: "Dolutegravir",
      dose: "regimen-based.",
    },
    {
      DrugGroup: "INFECTIONS / ANTIMICROBIALS",
      DrugSubGroup: "Antivirals",
      TypeofDrug: "HIV antivirals",
      medication: "Bictegravir",
      dose: "regimen-based.",
    },
    {
      DrugGroup: "INFECTIONS / ANTIMICROBIALS",
      DrugSubGroup: "Antivirals",
      TypeofDrug: "HIV antivirals",
      medication: "Raltegravir",
      dose: "regimen-based.",
    },
    {
      DrugGroup: "INFECTIONS / ANTIMICROBIALS",
      DrugSubGroup: "Antivirals",
      TypeofDrug: "Hepatitis antivirals",
      medication: "Sofosbuvir/ledipasvir",
      dose: "fixed combo OD.",
    },
    {
      DrugGroup: "INFECTIONS / ANTIMICROBIALS",
      DrugSubGroup: "Antivirals",
      TypeofDrug: "Hepatitis antivirals",
      medication: "Sofosbuvir/velpatasvir",
      dose: "fixed combo OD.",
    },
    {
      DrugGroup: "INFECTIONS / ANTIMICROBIALS",
      DrugSubGroup: "Antivirals",
      TypeofDrug: "Hepatitis antivirals",
      medication: "Glecaprevir/pibrentasvir",
      dose: "fixed combo OD.",
    },
    {
      DrugGroup: "INFECTIONS / ANTIMICROBIALS",
      DrugSubGroup: "Antivirals",
      TypeofDrug: "RSV antivirals",
      medication: "Palivizumab",
      dose: "15 mg/kg monthly (paediatric specialist).",
    },
    {
      DrugGroup: "INFECTIONS / ANTIMICROBIALS",
      DrugSubGroup: "Antiparasitics",
      TypeofDrug: "Antimalarials",
      medication: "Artemether/lumefantrine",
      dose: "fixed-dose combo, 6 doses over 3 days.",
    },
    {
      DrugGroup: "INFECTIONS / ANTIMICROBIALS",
      DrugSubGroup: "Antiparasitics",
      TypeofDrug: "Antimalarials",
      medication: "Chloroquine",
      dose: "regimen-based loading over 24 h.",
    },
    {
      DrugGroup: "INFECTIONS / ANTIMICROBIALS",
      DrugSubGroup: "Antiparasitics",
      TypeofDrug: "Antimalarials",
      medication: "Atovaquone/proguanil",
      dose: "4 tablets OD ×3 days (treatment).",
    },
    {
      DrugGroup: "INFECTIONS / ANTIMICROBIALS",
      DrugSubGroup: "Antiparasitics",
      TypeofDrug: "Antiprotozoals",
      medication: "Tinidazole",
      dose: "2 g stat (some indications).",
    },
    {
      DrugGroup: "INFECTIONS / ANTIMICROBIALS",
      DrugSubGroup: "Antiparasitics",
      TypeofDrug: "Antihelminthics",
      medication: "Albendazole",
      dose: "400 mg stat (longer courses some infections).",
    },
    {
      DrugGroup: "INFECTIONS / ANTIMICROBIALS",
      DrugSubGroup: "Antiparasitics",
      TypeofDrug: "Antihelminthics",
      medication: "Mebendazole",
      dose: "100 mg stat.",
    },
    {
      DrugGroup: "INFECTIONS / ANTIMICROBIALS",
      DrugSubGroup: "Antiparasitics",
      TypeofDrug: "Antihelminthics",
      medication: "Ivermectin",
      dose: "150–200 micrograms/kg stat.",
    },

    // --- ENDOCRINE SYSTEM (Missing Items) ---
    {
      DrugGroup: "ENDOCRINE SYSTEM",
      DrugSubGroup: "Diabetes drugs",
      TypeofDrug: "Metformin",
      medication: "Metformin MR",
      dose: "start 500–750 mg OD → 1.5–2 g OD.",
    },
    {
      DrugGroup: "ENDOCRINE SYSTEM",
      DrugSubGroup: "Diabetes drugs",
      TypeofDrug: "Sulfonylureas",
      medication: "Glimepiride",
      dose: "1 mg OD → 4–6 mg OD.",
    },
    {
      DrugGroup: "ENDOCRINE SYSTEM",
      DrugSubGroup: "Diabetes drugs",
      TypeofDrug: "TZDs",
      medication: "Pioglitazone",
      dose: "15–30 mg OD → 45 mg OD.",
    },
    {
      DrugGroup: "ENDOCRINE SYSTEM",
      DrugSubGroup: "Diabetes drugs",
      TypeofDrug: "DPP-4 inhibitors",
      medication: "Linagliptin",
      dose: "5 mg OD.",
    },
    {
      DrugGroup: "ENDOCRINE SYSTEM",
      DrugSubGroup: "Diabetes drugs",
      TypeofDrug: "SGLT2 inhibitors",
      medication: "Canagliflozin",
      dose: "100–300 mg OD.",
    },
    {
      DrugGroup: "ENDOCRINE SYSTEM",
      DrugSubGroup: "Diabetes drugs",
      TypeofDrug: "SGLT2 inhibitors",
      medication: "Ertugliflozin",
      dose: "5–15 mg OD.",
    },
    {
      DrugGroup: "ENDOCRINE SYSTEM",
      DrugSubGroup: "Diabetes drugs",
      TypeofDrug: "GLP-1 agonists",
      medication: "Exenatide",
      dose: "5 micrograms BD → 10 micrograms BD; LA 2 mg weekly.",
    },
    {
      DrugGroup: "ENDOCRINE SYSTEM",
      DrugSubGroup: "Diabetes drugs",
      TypeofDrug: "GLP-1 agonists",
      medication: "Liraglutide",
      dose: "0.6 mg OD → 1.2–1.8 mg OD.",
    },
    {
      DrugGroup: "ENDOCRINE SYSTEM",
      DrugSubGroup: "Diabetes drugs",
      TypeofDrug: "GLP-1 agonists",
      medication: "Dulaglutide",
      dose: "0.75–1.5 mg weekly.",
    },
    {
      DrugGroup: "ENDOCRINE SYSTEM",
      DrugSubGroup: "Diabetes drugs",
      TypeofDrug: "GLP-1 agonists",
      medication: "Semaglutide SC",
      dose: "0.25 mg weekly → 0.5–1 mg weekly.",
    },
    {
      DrugGroup: "ENDOCRINE SYSTEM",
      DrugSubGroup: "Diabetes drugs",
      TypeofDrug: "Insulins",
      medication: "Bolus insulin",
      dose: "~0.1–0.2 units/kg per meal.",
    },
    {
      DrugGroup: "ENDOCRINE SYSTEM",
      DrugSubGroup: "Diabetes drugs",
      TypeofDrug: "Insulins",
      medication: "Mixed insulin",
      dose: "10–12 units with main meals, titrated.",
    },
    {
      DrugGroup: "ENDOCRINE SYSTEM",
      DrugSubGroup: "Corticosteroids",
      TypeofDrug: "Corticosteroids",
      medication: "Hydrocortisone (replacement)",
      dose: "15–30 mg/day PO in divided doses.",
    },
    {
      DrugGroup: "ENDOCRINE SYSTEM",
      DrugSubGroup: "Corticosteroids",
      TypeofDrug: "Corticosteroids",
      medication: "Dexamethasone",
      dose: "0.5–16 mg/day depending on indication.",
    },
    {
      DrugGroup: "ENDOCRINE SYSTEM",
      DrugSubGroup: "Thyroid drugs",
      TypeofDrug: "Thyroid drugs",
      medication: "Liothyronine",
      dose: "10–20 micrograms 2–3×/day.",
    },
    {
      DrugGroup: "ENDOCRINE SYSTEM",
      DrugSubGroup: "Thyroid drugs",
      TypeofDrug: "Thyroid drugs",
      medication: "Propylthiouracil",
      dose: "100–150 mg TDS initially.",
    },
    {
      DrugGroup: "ENDOCRINE SYSTEM",
      DrugSubGroup: "Contraception",
      TypeofDrug: "Progestogen-only pill",
      medication: "Typical POP",
      dose: "1 tablet OD continuous.",
    },
    {
      DrugGroup: "ENDOCRINE SYSTEM",
      DrugSubGroup: "Contraception",
      TypeofDrug: "LARC",
      medication: "Etonogestrel implant",
      dose: "68 mg SC, lasts 3 years.",
    },
    {
      DrugGroup: "ENDOCRINE SYSTEM",
      DrugSubGroup: "Contraception",
      TypeofDrug: "LARC",
      medication: "Levonorgestrel IUS",
      dose: "e.g. 52 mg device releasing ~20 micrograms/day, 3–8 years efficacy.",
    },
    {
      DrugGroup: "ENDOCRINE SYSTEM",
      DrugSubGroup: "Contraception",
      TypeofDrug: "LARC",
      medication: "Copper IUD",
      dose: "5–10 years depending on device.",
    },
    {
      DrugGroup: "ENDOCRINE SYSTEM",
      DrugSubGroup: "HRT",
      TypeofDrug: "HRT",
      medication: "Estradiol oral",
      dose: "1–2 mg OD.",
    },
    {
      DrugGroup: "ENDOCRINE SYSTEM",
      DrugSubGroup: "HRT",
      TypeofDrug: "HRT",
      medication: "Estradiol patches",
      dose: "25–100 micrograms/24 h, changed 1–2×/week.",
    },
    {
      DrugGroup: "ENDOCRINE SYSTEM",
      DrugSubGroup: "HRT",
      TypeofDrug: "HRT",
      medication: "Combined oestrogen/progestogen",
      dose: "fixed oral or patch regimens.",
    },

    // --- MUSCULOSKELETAL & JOINT (Missing) ---
    {
      DrugGroup: "MUSCULOSKELETAL & JOINT",
      DrugSubGroup: "COX-2 inhibitors",
      TypeofDrug: "COX-2 inhibitors",
      medication: "Celecoxib",
      dose: "100–200 mg BD.",
    },
    {
      DrugGroup: "MUSCULOSKELETAL & JOINT",
      DrugSubGroup: "COX-2 inhibitors",
      TypeofDrug: "COX-2 inhibitors",
      medication: "Etoricoxib",
      dose: "30–120 mg OD.",
    },
    {
      DrugGroup: "MUSCULOSKELETAL & JOINT",
      DrugSubGroup: "Muscle relaxants",
      TypeofDrug: "Muscle relaxants",
      medication: "Tizanidine",
      dose: "2–4 mg BD–TDS.",
    },
    {
      DrugGroup: "MUSCULOSKELETAL & JOINT",
      DrugSubGroup: "Osteoporosis",
      TypeofDrug: "Osteoporosis",
      medication: "Risedronate",
      dose: "35 mg weekly or 5 mg OD.",
    },
    {
      DrugGroup: "MUSCULOSKELETAL & JOINT",
      DrugSubGroup: "Osteoporosis",
      TypeofDrug: "Osteoporosis",
      medication: "Ibandronic acid",
      dose: "150 mg monthly or IV q3m.",
    },
    {
      DrugGroup: "MUSCULOSKELETAL & JOINT",
      DrugSubGroup: "Osteoporosis",
      TypeofDrug: "Osteoporosis",
      medication: "Denosumab",
      dose: "60 mg SC q6m.",
    },
    {
      DrugGroup: "MUSCULOSKELETAL & JOINT",
      DrugSubGroup: "Osteoporosis",
      TypeofDrug: "Osteoporosis",
      medication: "Teriparatide",
      dose: "20 micrograms SC OD.",
    },
    {
      DrugGroup: "MUSCULOSKELETAL & JOINT",
      DrugSubGroup: "Gout",
      TypeofDrug: "Gout",
      medication: "Febuxostat",
      dose: "80–120 mg OD.",
    },
  ];

  const medicationsWithDefaults = medications.map((med) => ({
    ...med,
    added_by: "1",
    org_id: null,
    created_at: new Date(),
    updated_at: new Date(),
  }));

  return knex.batchInsert("medications_list", medicationsWithDefaults, 50);
};

exports.down = function (knex) {
  return knex("medications_list").where("added_by", "Admin").del();
};
